runtimeverification/llvm-backend

- .gitmodules
- runtime/header.ll
There isn't much actual code here, but I've laid out how I propose that we represent each type of K term as well as how I propose we allocate them, deallocate them, and trace them for garbage collection. It does also include the representation of the types in terms of llvm types.
I would appreciate thorough feedback prior to moving on because a lot of the code we can write after this point will be dependent on this representation.
> header of every file in llvm runtime: defines types

- ciscript
- include/kllvm/ast/AST.h
- include/kllvm/codegen/CreateTerm.h
- lib/ast/AST.cpp
- lib/codegen/CreateTerm.cpp
- lib/parser/KOREScanner.l
- test/imp.kore
- test/imp.ll
- test/test.kore
- test/test.ll
- tools/test_rhs/CMakeLists.txt
- tools/test_rhs/main.cpp
I have tested each feature I added by manually examining the code it generates in a single case, and I have tested that the generated code compiles, and added coverage of each feature to the ci testing, but I have not manually gone through the entire reference files.
That said, we can now handle 182 of the 183 axioms in imp.kore. The single missing case is injection transitivity which is polymorphic over its sorts and therefore must generate different code depending on the SortCategory of its argument. I will fix this in the next pull request.
> Expand rhs generation to cover many more features

- CMakeLists.txt
- bin/llvm-kompile
- runtime/alloc/collect.c
- runtime/datastructures/src/decls.rs
- runtime/rustalloc.ll
- rustalloc.alias
- rustalloc.lds
Fixes a bug where we were still using malloc to allocate rust objects. Also fixes an issue where code generation generated a call to 0 for the __rust_alloc function.
> Improvements to rust allocation

- matching/src/KorePatterns.hs
- matching/src/Pattern/Parser.hs
I checked the pattern synonyms that the Kore team created to see if we could use them, at Brandon's suggestion. What I found is that these pattern synonyms apply to ASTs that have not been unified (= normal patterns), while our code uses unified ASTs everywhere. 
One solution would be to transform the AST into normal patterns, match them and the turn them back into unified patterns. This seemed both time consuming and inefficient.
The other solution would be to change all the code to use normal ASTs. This would be a major change that could be eventually done in a separate commit. In order to support it I created some pattern synonyms that work with unified ASTs that have the same name as the one in Kore. So it would only be a matter of changing the place that we import them from.
> Add pattern synonyms to splitFunction and splitTop

- lib/ast/AST.cpp
- matching/src/Pattern/Parser.hs
We previously had the wrong form to axioms about top level rewrites. I am keeping the old syntax working for backwards compatibility, but adding the new syntax as well.
This will go with an upcoming PR of k that I will tag this PR in.
> Fix llvm backend for when k-to-kore gets top level rewrites fixed

- matching/package.yaml
- matching/src/Pattern.hs
- matching/src/Pattern/Class.hs
- matching/src/Pattern/Gen.hs
- matching/src/Pattern/Map.hs
- matching/src/Pattern/Optimiser/Score.hs
- matching/src/Pattern/Set.hs
- matching/src/Pattern/Type.hs
- matching/src/Pattern/Var.hs
- matching/test/Spec.hs
Replace patterns with type variables.
Even though this change seems to be quite large only two small changes have been done that ripple through all the sources.
1. Change the data types to begin abstracting away patterns.
We have two patterns: Pattern and BoundPattern that should be abstracted away in order to properly decouple the code. This first change removed by-name references to patterns from the data types, but still keeps them in the rest of the code.
2. Remove the Constructor reference from the Pattern constructor.
The Constructor data type also includes Map/Set/List constructors, and the corresponding Pattern data constructor is always instantiated with Symbols or Literals.
This change has two benefits:
a. It's more type-safe since now by construction you can only use symbols or …
> Pattern cleanup

- Dockerfile
- Jenkinsfile
Ready for review. This should speed up the build by caching as many dependencies as we can.
> use docker to build dependencies

- matching/src/Everything.hs
I encountered a bug where llvm-kompile-matching was failing because the score function was choosing a column with an unbound map key. Turns out the reason for this was that we were computing the score of a map value as infinity and then multiplying that score by zero, which yielded a score of NaN for the column. I have fixed the bug and also introduced a error condition so that we will more quickly catch errors when the score is NaN.
> Fix NaN score bug

- include/runtime/alloc.h
- lib/codegen/CreateTerm.cpp
- lib/codegen/EmitConfigParser.cpp
- runtime/alloc/alloc.c
- runtime/alloc/collect.c
- runtime/strings/bytes.cpp
- runtime/strings/strings.cpp
This PR implements a garbage collection for the old generation. It uses the same copy-collector infrastructure for the old generation. For now, the old generation is collected every 10 young generation collections. We can change this in future by adding desirable logic in the `shouldCollectOldGen` function. It is tested with the EVM vm and blockchain tests.
> Garbage collection for the old generation

- install-rust
> OSX does not come with coreutils and thus does not have sha512sum.

- runtime/io/io.cpp
It seems that there were some implicit declarations of errno and std::string that existed on linux but not mac os.
> fix build errors on mac

- Dockerfile
- INSTALL.md
- bin/llvm-kompile
- bin/llvm-kompile-clang
- bin/llvm-kompile-rust-lto
- cmake/mkrlib.cmake
We could not do this previously due to the rust version mismatch issue, but it is now possible. It seems to have uncovered a bug in gold though, so we switch to using lld as our linker.
Interestingly, it seems one rust standard library crate, libbacktrace_sys, contains non-rust object files contained inside of it. This mandated a fix to the llvm-kompile-rust-lto script.
> Lto rust standard library

- matching/src/main/scala/org/kframework/backend/llvm/matching/Matrix.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/Pattern.scala
With these changes and the others I have already made elsewhere, we can finally generate the decision trees for the linking semantics.
Includes:
* A Fix for maxListSize and AsP
* A bug in AsP.toShortString
* bugfix for crash in overload children
* Fix overload children through AsP.
> Fixes for decision tree generation for linking semantics

- include/runtime/header.h
This PR makes move_int part of the runtime API because it is needed by the blockchain plugin of the K evm semantics.
> Make move_int part of the runtime API

- ciscript
- include/kllvm/codegen/Decision.h
- lib/codegen/Decision.cpp
- matching/src/main/scala/org/kframework/backend/llvm/matching/Matching.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/Matrix.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/dt/DecisionTree.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/Pattern.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/SortCategory.scala
- runtime/equality.ll
- test/test19.in.kore
- test/test19.kore
- test/test19.out.kore
Substantially improves sharing of set/map choice operations using the indirectbr instruction. Also includes a minor fix for booleans, which put together allow the C/C++ linking semantics to link successfully.
> Refactor set/map choice

- ciscript
- include/runtime/alloc.h
- include/runtime/arena.h
- lib/codegen/CreateTerm.cpp
- lib/codegen/Decision.cpp
- runtime/alloc/alloc.c
- runtime/alloc/arena.c
- runtime/strings/strings.cpp
- test/test-gc-alwaysgc-1.kore
- test/test-gc-alwaysgc.kore
This PR eliminates allocations in the not collected arena for sret paremeters of llvm functions generated by the backend. Instead, a new arena is introduced that is always fully collected in every collection and the sret parameters are allocated there when needed. This is OK, since these allocations are not supposed to to be live between steps.
Addresses #45
> Elimination of no-gc allocations for sret parameters

- CMakeLists.txt
- bin/llvm-krun
This is a basic script that constructs the initial configuration from a parsed set of configuration variables and invokes the interpreter. It's not currently needed by the K frontend, but it makes it considerably easier to invoke the interpreter without calling krun.
> llvm-krun script

- lib/codegen/Decision.cpp
Don't generate phi nodes for basic blocks with only a single predecessor.
> remove spurious phi nodes

- matching/src/main/java/org/kframework/backend/llvm/matching/NamedHeuristic.java
- matching/src/main/scala/org/kframework/backend/llvm/matching/Heuristics.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
Ready for review. We cut some corners when we're checking the reflection. Namely, we don't check that the annotation is a NamedHeuristic and we assume heuristics always have exactly one annotation, but since it's a sealed trait, this is basically fine unless we at some point need to violate those properties.
Good news is, code will now crash if you forget to give a heuristic a name.
> use reflection and annotations to give heuristics names

- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/Pattern.scala
Basically we assume that builtins don't have actual symbol constructors even if the user declares them, so we filter out such cases from the decision tree. this fixes a bug where code generation crashes due to a macro.
> fix bug when user defines subsort of builtin sort

- bin/llvm-kompile-clang
- include/runtime/alloc.h
- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/Pattern.scala
- runtime/alloc/alloc.c
- runtime/alloc/arena.c
- runtime/datastructures/src/hook_list.rs
Includes:
* bug fix where llc was undesirably optimizing by default
* bug fix where we were overflowing the end of a memory block because we were writing sentinels to the NoGC space which is not 8-byte aligned
* Bug fix to decision tree generation that fixes wasm bug
* Fix bug where our hash algorithm for lists was broken the same way the set and map algorithm was previously.
> Misc bug fixes

- CMakeLists.txt
- install-rust
It looks like the bug in llvm 7 that broke the llvm backend was fixed in llvm 7.0.1, which, while not available on Ubuntu 18.04, is available in Debian Buster, whereas llvm 8 is not. So I'm going to add support for it here.
> Support llvm 7.0.1

- include/runtime/header.h
This provides a better way to loop through Set and Map terms from C/C++.
> expose iteration primitives to C runtime

- lib/codegen/EmitConfigParser.cpp
It seems the overload we were calling before exists in llvm 7 but creates a badref. Hopefully this should fix the debian build.
> don't pass type to LoadInst

- runtime/configurationparser/ConfigurationPrinter.cpp
GDB doesn't really work on Mac OS anyway so it doesn't help much to have this code. But it doesn't compile on Mac OS so we disable it.
> don't embed gdb code on Mac OS

- unittests/runtime-collections/lists.cpp
- unittests/runtime-collections/maps.cpp
Clang 7 segfaults when you try to initialize a flexible array member with a brace-init-list. I tested this fix and it fixes the segfault while also passing tests.
> fix segfault on clang 7

- include/runtime/collect.h
- runtime/alloc/alloc.cpp
- runtime/collect/collect.cpp
freeAllKoreMem doesn't work with the latest garbage collection algorithm because it broke the hack that allowed us to allocate the empty collections with malloc. However, freeAllKoreMem was itself essentially a hack for use in kevm-vm to get around the fact that garbage collection was not yet complete and did not collect everything. So instead, we simply call koreCollect from freeAllKoreMem with the empty list of roots. This will free everything /except/ the collection nodes implicitly reached from static variables in immer, because we still treat them as roots due to the call to migrateRoots.
> use koreCollect to "free" all memory

- lib/parser/KOREScanner.l
In kframework/kore#922, we begin to use set variables in `prelude.kore`, which requires this small extension to the C++ Kore parser.
> KOREScanner.l: Admit @ in identifiers for set variables

- matching/src/main/config/checkstyle-java.xml
- matching/src/main/scala/org/kframework/backend/llvm/matching/Constructor.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/Generator.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/Matching.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/Matrix.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/Pattern.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/SortCategory.scala
We only generate the non exhaustive warnings for functions marked as total with the `functional` attribute. We only generate the useless clause warning if a location exists for the rule (otherwise it was generated by the compiler).
Tested for correctness against IMP and KEVM. Tested that it doesn't crash additionally against MKR-MCD, WASM, and Beacon Chain.
> Generate useless clause and non exhaustive function warnings

- include/kllvm/ast/AST.h
- include/kllvm/codegen/CreateTerm.h
- include/kllvm/codegen/Debug.h
- include/kllvm/codegen/Decision.h
- include/kllvm/codegen/DecisionParser.h
- include/kllvm/parser/KOREParserDriver.h
- lib/ast/AST.cpp
- lib/codegen/CreateTerm.cpp
- lib/codegen/Debug.cpp
- lib/codegen/Decision.cpp
- lib/codegen/DecisionParser.cpp
- lib/codegen/EmitConfigParser.cpp
- lib/parser/KOREParser.y
- lib/parser/KOREParserDriver.cpp
- lib/parser/KOREScanner.l
- runtime/configurationparser/ConfigurationParser.cpp
- tools/llvm-kompile-codegen/main.cpp
- unittests/compiler/asttest.cpp
This is the first of two refactorings to the parser I am making in order to ensure that memory associated with KOREDefinition etc is freed after calls to parseConfiguration. Here we delete the meta level stuff because it is no longer a part of the syntax of KORE.
> remove meta level from parser

- Jenkinsfile
-   Trigger auto-update of LLVM backend submodule on `master` branch.
-   Send slack message on failing `master` branch tests.
-   Global timeout on testing phase.
> Slight improvements to Jenkinsfile testing

- runtime/alloc/arena.cpp
We don't actually need to include jemalloc.h to use the jemalloc implementation of malloc, and we aren't using anything else in that header, so I am removing the include of this header as it seems to break the build on Mac OS Catalina.
> remove jemalloc.h which is unused

- CMakeLists.txt
Apparently if you don't specify a version cmake doesn't necessarily prefer newer versions to older versions, so we need to do this explicitly after all.
> Llvm 9 better version

- include/runtime/header.h
- runtime/io/io.cpp
- runtime/strings/strings.cpp
- unittests/runtime-io/io.cpp
Previously we were only calling read once per file descriptor when we called the system hook. This is bad because it means it won't read the entire output if the output is longer than the buffer size. We were also setting the length of the string equal to the length of the buffer instead of to the number of characters read.
This PR should fix the behavior by allocating string buffers on the KORE heap and using `select` to multiplex reading from stderr and stdout until both have been read to completion, at which time it converts the string buffers into strings. We didn't detect this error before because we were not asserting anything in our unit tests about the length of the string returned, only about the first five characters of the string. So I fixed the unit tests as well.
> fix system hook

- lib/ast/CMakeLists.txt
- lib/parser/CMakeLists.txt
- runtime/CMakeLists.txt
Even when building a release build of the llvm backend, we generally want the ability to do debug builds of K definitions. This requires building the llvm backend runtime with debug symbols. So we modify the CMake scripts so that debug symbols are always enabled on runtime components, regardless of the configuration mode selected.
> always enable dwarf info in runtime

- test/Makefile
I realized today that we were not actually checking correctly that the diff and grep commands in our test harness reported no errors, inside the tests that test multiple programs with a single definition. This PR fixes that oversight, but fortunately there are no regressions that resulted from it.
> fix test harness when one definition has multiple tests

- bin/llvm-kompile-clang
Arch linux patched llvm so that position independent executables were enabled by default by clang and lld, but not llc :/
So we need to pass --relocation-model=pic manually to llc when we invoke llc otherwise we will get a bunch of arcane linker errors.
Fixes #243
> fix arch debug builds

- gdb/kllvm.py
- include/kllvm/codegen/Debug.h
- lib/codegen/CreateTerm.cpp
- lib/codegen/Debug.cpp
- lib/codegen/Decision.cpp
- lib/codegen/EmitConfigParser.cpp
Fixes #272 
This should fix both injections and tokens being pretty printed with the wrong sorts.
> Correctly print sorts of terms in gdb

- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
Previously we were paying a quadratic cost in the number of axioms in the KORE definition in order to expand all the aliases. This is okay for definitions up to a certain point, but explodes the time spent generating decision trees once the size of the definition gets beyond a certain point. This was simply an oversight, though, and we are able to compute the necessary information in linear time. So here we do just that.
> more performant alias expansion

- bin/llvm-kompile-clang
I accidentally mangled the symbol name for linux instead of mac os before.
> fix typo in previous bugfix PR

- matching/src/main/scala/org/kframework/backend/llvm/matching/Matching.scala
250 characters
We previously ran into an issue where because we were using symbol names as file names for the decision trees of functions, we would get a unix error if the symbol name had >250 characters, because the filename would exceed the 255 character limit of path components on unix. We fixed this by creating an index from symbol names to filenames and trimmed the filenames to their initial 250 characters. However, this has the effect that if there are multiple symbols with the same initial 250 characters, their decision trees overwrite one another, which leads to some of those functions seeing a decision tree intended for another function, which causes the code generation phase to crash with an error.
In order to fix this, we simply create a unique integer variable and append it to …
> don't use the same filename for multiple symbols with identical initial

- bin/llvm-krun
- runtime/configurationparser/ConfigurationPrinter.cpp
- runtime/finish_rewriting.ll
I discovered some more portability issues. One involves stderr, which is not a symbol on mac OS but a macro, and another involves reliance on bash 4 associative arrays in the llvm-krun script, when bash is still version 3 on mac os.
With these changes, the IMP example in the k frontend now passes on mac os.
> Fix llvm backend on mac os

- include/kllvm/codegen/CreateTerm.h
- include/kllvm/codegen/Decision.h
- include/kllvm/codegen/DecisionParser.h
- lib/codegen/CreateTerm.cpp
- lib/codegen/Decision.cpp
- lib/codegen/DecisionParser.cpp
- matching/src/main/scala/org/kframework/backend/llvm/matching/Heuristics.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/Matrix.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/dt/DecisionTree.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/Pattern.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/SortCategory.scala
- tools/llvm-kompile-codegen/main.cpp
In the process of testing the llvm backend on the K tutorial, I uncovered a number of bugs associated with nondeterministic set and map choices.
Roughly, there were three bugs:
1. Phi nodes for variables that are needed on only one ancestor path of a shared node with multiple choice nodes as ancestors were not being computed correctly if that shared node only had a single immediate parent.
2. The choice to be jumped back to after an iterator for a choice runs out of elements was incorrect for nested choice nodes that are shared across multiple different parent choices.
3. If both children of a switch that checks whether the iterator of a choice has run out of elements have nested choice nodes, the code was not correctly computing the jump destination after entering the outer switch.
The …
> Clean up choice code to fix bugs

- lib/codegen/Decision.cpp
We were accidentally incrementing idx twice in each loop iteration, which means only every other child of the function symbol was being initialized. obviously, this corrupts memory since you end up reading zeroed bytes.
> fix double loop pointer increment

- Jenkinsfile
- include/kllvm/codegen/Decision.h
- lib/codegen/Decision.cpp
It was reported to me that the previous choice PR caused regressions in the C execution semantics, primarily because it exploded the size of the stack frame of the step function, leading to a stack overflow. After analyzing the code, I determined this to be due to the fact that liveness analysis was incorrectly marking variables live in basic blocks due to a path to their use that passed through the failure block, even though static analysis of the control flow graph ought to be able to determine those paths to be infeasible. Fixing this required us to keep track of which choice ancestors cause variables to become live in a block, and removing them from the live variables if they are made live by choice nodes that are no longer an ancestor of that block after propagating to one or more …
> Fix choice stack size explosion

- CMakeLists.txt
Chris is no longer blocked on this, but this is the fix for the issue he reported. LLVM's cmake package does not appear to distinguish between find_package asking for any version of llvm 7, versus asking specifically for version 7.0. Which means we need an extra case in here for minor versions. We support any version of llvm greater than or equal to 7.0.1, and 7.1 is the only minor version that has been released since then.
> cmake fix for llvm 7.1

- include/kllvm/codegen/Decision.h
- lib/codegen/Decision.cpp
the K build is failing on Mac OS because llvm 9 introduced some new optimizations that take advantage of undefined values in llvm IR, and this uncovered a bug in how we are computing the phi nodes for decision tree functions in the llvm backend. Essentially, we were not correctly computing the set of choice nodes that are ancestors of the current node, and that led to values getting assigned as undefined when really liveness should have treated them as live. This meant that the same stack slot was being reused for multiple different variables and their values were clobbering one another, leading to memory corruption in the substitution that was being generated by the decision tree.
Essentially, to fix this, instead of doing a DFS on the tree to compute the choice ancestors, we first do a …
> Fix another bug involving phi nodes and choices in decision trees

- bin/llvm-kompile
- include/kllvm/codegen/Decision.h
- lib/codegen/Decision.cpp
The liveness analysis we were doing was proving to be very slow, so I went digging into the details of how SSA is usually constructed, and realized that it's usually done based on dominance frontiers rather than data flow equations. I was going to implement all of that, but then I realized we were probably better off just relying on the mem2reg llvm transformation pass. This turns out to delete a bunch of code /and/ be much much faster, while being much less likely to have bugs. So it's win/win/win.
> remove a bunch of stuff and just use alloca + mem2reg

- bin/llvm-kompile
Previously we were relying on instcombine to combine phi nodes together sufficiently to prevent the stack space from exploding. Now that we are using mem2reg to create the phi nodes, the phi nodes created are already minimal and instcombine is (hopefully) not necessary in order to prevent stack overflows. Removing it from the calls will decrease the time that it takes to kompile.
> don't call instcombine anymore unless we are actually optimizing

- runtime/collect/collect.cpp
Previously we were writing the forwarding pointer for integers during garbage collection into the first limb of the integer. This works on Ubuntu still and worked for some time on Arch linux and Mac OS, but has since stopped working, as can be seen by the fact that llvm backend programs segfault on those OSes. I suspect this has to do with the release of GMP 6.2 last month, which has only very recently made its way to the package managers due to how important it is for system stability since extremely major packages like gcc depend on it. It probably broke sometime while the k release job was broken and we are only now realizing it as I have fixed the other issues with the K release.
Essentially, the problem that was discovered is that when _mp_alloc is zero, no limbs have been allocated …
> fix bug where we migrate integers with no limbs improperly

- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/SortCategory.scala
We commonly see users confused by the exception that gets thrown by the llvm backend if they do not specify that a cell collection with `multiplicity="*"` is either a set or a map. So I decided to add a more informative error message at the location where this occurs.
> add more informative error when user uses bags in cells

- matching/src/main/scala/org/kframework/backend/llvm/matching/Matrix.scala
Essentially, we try to evaluate columns that match on variables before we evaluate columns that need to perform a map or set choice because the map or set key contains those variables. This significantly helps reduce the number of unnecessary choices present in the decision tree by converting as many as possible into concrete lookups. However, we were too aggressively applying this requirement in cases where both columns need to perform a map or set choice to match a particular variable. In this case, the dependency was circular, so both columns were being delayed until the very end of the matching process, which ends up significantly reordering the matching order in ways that significantly increase the size of the decision tree. This was leading to a stack overflow on the execution …
> columns are also valid if all the columns they need also need them

- include/runtime/header.h
- runtime/configurationparser/ConfigurationPrinter.cpp
- runtime/finish_rewriting.ll
- runtime/main/main.ll
- runtime/take_steps.ll
This is the first of two PRs needed in order to allow users to get the number of rewrite steps the llvm backend took before terminating.
> print statistics from llvm backend when requested

- Jenkinsfile
- lib/codegen/EmitConfigParser.cpp
- test/defn/test35.kore
- test/input/test35.in.kore
- test/output/test35.out.diff.kore
This is a fairly straightforward memory corruption issue in the llvm backend. When the initial configuration has a non-hooked function that returns a term of sort List, it was storing a pointer to that list to a list** object allocated by malloc and then accidentally treating that list** as if it was a list*. This obviously led to memory corruption. This is left over from the days when we were trying to return structs by value from functions in the llvm backend. However, all structs are returned as pointers now in the llvm backend, which means that this code had become out of date and we didn't realize because there were no tests covering this case. I added a test to cover the case when the initial configuration has a function that returns sort List, and fixed the code so that it directly …
> Fix memory corruption when initial configuration has a List in it

- bin/llvm-kompile-testing
- matching/src/main/scala/org/kframework/backend/llvm/matching/Matrix.scala
We accidentally misrepresented the `necessary` function by checking that a row was not useless when we should have been checking that it *was* useless. This was seriously nerfing the p and n heuristics and making them compute the wrong thing. I tested the modified p heuristic on the tezos semantics and while it takes longer than the q heuristic, the resulting decision tree is not any larger and has a slightly smaller average path length.
> fix p and n heuristic

- bin/llvm-krun
- include/kllvm/ast/AST.h
- lib/ast/AST.cpp
- tools/CMakeLists.txt
- tools/kprint/CMakeLists.txt
- tools/kprint/main.cpp
This is the llvm backend part of a pair of PRs used to support pretty-printing kore terms with a vastly reduced overhead. Some logic is not implemented yet, but it is sufficient to unparse some simple IMP programs. I will add more features as I go if this proves useful to people.
Second PR is here: https://github.com/kframework/k/pull/1211
> llvm backend pretty printing tool

- lib/ast/AST.cpp
- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
This attribute is applied to, among other things, `\ceil` axioms, and should be treated as if the axiom does not exist in the llvm backend.
> ignore axioms with simplification attribute

- gdb/kllvm.py
- include/kllvm/ast/AST.h
- include/kllvm/codegen/CreateTerm.h
- include/kllvm/codegen/Debug.h
- lib/ast/AST.cpp
- lib/codegen/CreateTerm.cpp
- lib/codegen/Debug.cpp
- tools/kprint/main.cpp
- tools/llvm-kompile-codegen/main.cpp
This uses the kprint command and thus only works if the kompiled directory still exists in the same location on disk. However, with this, we can step through programs in gdb and get colorized and pretty-printed output. Because it uses the kprint command, details of pretty-printing are divorced from gdb.
> Pretty print terms in gdb by default.

- lib/codegen/Util.cpp
- unittests/runtime-io/io.cpp
Clang 10 reports a warning here because we were accidentally comparing a `char *` with != instead of first converting it to a std::string.
> fix more llvm 10 bugs

- lib/ast/AST.cpp
- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
This reverts commit 616237b488ae238583558b03a66b02d71454914c.
This commit broke the C semantics and it seems that we will need a more complex fix to the problem that this fixed, so I am reverting this for now so that we aren't in a broken state while we figure out the better solution.
> Revert "ignore axioms with simplification attribute (#316)"

- lib/ast/AST.cpp
This was an off by one error that causes problems when the format attribute of a production references the ninth nonterminal.
> include nine in list of escape digits

- matching/src/main/scala/org/kframework/backend/llvm/matching/Matrix.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/SortCategory.scala
We will not treat a constructor that is an injection as if it makes the
match non-exhaustive if the sort injected into has no productions that
are not injections.
> fix non-exhaustiveness bug

- include/kllvm/ast/AST.h
- lib/ast/AST.cpp
- tools/kprint/main.cpp
Adds some new fixes for kprint, adding attribute data for the remaining connectives and prelude symbols, and fixes some bugs relating to formatting.
Sample input:
```
\and{SortGeneratedTopCell{}}(
Lbl'-LT-'generatedTop'-GT-'{}(
Lbl'-LT-'T'-GT-'{}(
Lbl'-LT-'k'-GT-'{}( dotk{}()),
Lbl'-LT-'state'-GT-'{}(
Lbl'Unds'Map'Unds'{}(
Lbl'UndsPipe'-'-GT-Unds'{}(
inj{SortId{}, SortKItem{}}(
\dv{SortId{}}( "a")
),
inj{SortInt{}, SortKItem{}}(
VarA:SortInt{}
)
),
Lbl'Unds'Map'Unds'{}(
Lbl'UndsPipe'-'-GT-Unds'{}(
inj{SortId{}, SortKItem{}}(
\dv{SortId{}}( "b")
),
inj{SortInt{}, SortKItem{}}(
VarB:SortInt{}
)
),
Lbl'UndsPipe'-'-GT-Unds'{}(
inj{SortId{}, SortKItem{}}(
\dv{SortId{}}( "max")
),
inj{SortInt{}, SortKItem{}}(
VarB:SortInt{}
)
)
))
)
),
Lbl'-LT-'generatedCounter'-GT-'{}(
VarDotVar00:SortInt{}
) …
```
> Make kprint work on symbolic configurations

- tools/kprint/main.cpp
This is to bring the behavior of kprint in alignment with the behavior of `kast -i kore -o pretty`.
> update format attribute of builtin brackets

- matching/src/main/scala/org/kframework/backend/llvm/matching/Matrix.scala
This is the second of three PRs that will serve to provide more fine-grained warning control in the K frontend.
> change exception type of warnings in llvm backend

- runtime/meta/ffi.cpp
Reason: at_quick_exit is not defined on OSX (see references in kframework/k#1580)
Note: I'm not sure if this PR is enough --- it seems like you want to handle FFI handles to these symbols specially --- but that seems to be irrelevant if the symbol doesn't exist on this platform. Hence this PR.
> ffi: do not consider at_quick_exit a private symbol on OSX

- include/runtime/arena.h
- runtime/alloc/arena.cpp
- runtime/collect/collect.cpp
This commit fixes a bug that occurs when a young collection cycle starts
in between filling up an old generation memory block, and the allocation
of a fresh block in the oldspace.
> fix bug involving garbage collection

- .github/workflows/test.yml
- default.nix
- nix/llvm-backend.nix
Prior versions used deprecated GitHub Actions features which are now removed.
> workflows: Update Nix actions

- CMakeLists.txt
- ciscript
- include/runtime/alloc.h
- include/runtime/arena.h
- lib/codegen/Decision.cpp
- runtime/alloc/alloc.cpp
- runtime/alloc/arena.cpp
- runtime/collect/collect.cpp
- runtime/take_steps.ll
What this does:
* removes the configurable "collect every N rewrite steps" parameter from the build system and the runtime API
* Tracks the total number of blocks allocated in the youngspace
* Collects after a rewrite step if the youngspace is almost full (ie, there is less than 1MB remaining and also the youngspace is over 95% the size it was after the last collection)
* adds a parameter that configures the initial size of the youngspace
The next steps are going to be to collect during an allocation if we don't have enough free space to allocate something, but this will require stack maps and so it has been deferred for a future PR.
I measured the code on the OpenZeppelin tests and they pass. They take about the same amount of time and use about the same amount of memory for most of the …
> Allocation-heuristic based collection interval

- bin/llvm-krun
- include/kllvm/ast/AST.h
- include/kllvm/parser/KOREParser.h
- lib/ast/AST.cpp
- lib/parser/KOREParser.cpp
- tools/CMakeLists.txt
- tools/kore-expand-macros/CMakeLists.txt
- tools/kore-expand-macros/main.cpp
- tools/kprint/main.cpp
This adds a new tool to the llvm backend, kore-expand-macros, which takes a kompiled directory and a pattern and returns the pattern with all macros expanded. It also will reverse expand alias macros when you invoke `kprint`.
> C++ macro expander

- runtime/meta/ffi.cpp
This fixes a regression found in the C semantics when building a version of K that includes the llvm backend commit e696645d5a50a7ad06d4fed392504bd50fe34ff4. What happens is that the Bytes object allocated by the FFI module isn't getting the bit set telling GC not to migrate the object, so it migrates the object, leading to corrupt memory when you try to read the bits via its original native address.
> set NOT_YOUNG_OBJECT_BIT on ffi alloc'd Bytes

- include/kllvm/ast/AST.h
- lib/ast/AST.cpp
- tools/kore-expand-macros/main.cpp
- tools/kprint/main.cpp
* Adds support for priority and owise attributes
* Fixes a bug involving nonlinear patterns
* Fixes a bug in how macros are recursively applied
* Fixes bugs involving macro matching modulo overloads
> Fix various flaws in macro expander

- nix/llvm-backend.nix
- unittests/CMakeLists.txt
- unittests/runtime-ffi/CMakeLists.txt
- unittests/runtime-ffi/lib/CMakeLists.txt
- unittests/runtime-io/CMakeLists.txt
This pull request would exclude the unit tests from the default CMake target. The targets will now be:
- `make`: (default) build the LLVM backend
- `make unittests`: build the unit tests
- `make run-unittests`: (depends on `unittests`) build and run the unit tests
> Exclude unit tests from default CMake target

- include/kllvm/ast/AST.h
- lib/ast/AST.cpp
- runtime/configurationparser/ConfigurationParser.cpp
When executing one cFS OSAL test case with the new c-semantics, the default destructor of `KOREPattern` was causing a stack overflow right after the translated program in KORE was parsed. I propose an alternative destruction scheme for `KOREPattern` - one which does not do recursive calls and thus does not overflow.
This was tested only with the c-semantics. @dwightguth do you have any idea how and where to write a test case for parsing which would be a part of this repository?
> Fix stack overflow when destructing the parsed KORE

- cmake/LLVMKompile2.cmake
This fixes an issue reported by @malturki where if you are using LLVMKompile2.cmake to build your interpreter, and you modify a .k file and nothing else, it doesn't rerun the linking step, leading to an out of date interpreter even though make thinks everything is up to date.
> fix bug in LLVMKompile2.cmake

- bin/llvm-krun
Part 1 in fixing: https://github.com/kframework/k/issues/1844
Don't print the map stop if there are no config vars
I ran the `regression-new` tests on my machine and they still pass, and the reported issue disappeared.
Added proper tests in https://github.com/kframework/k/pull/1853
> Fix no config vars crash

- lib/codegen/EmitConfigParser.cpp
- runtime/configurationparser/ConfigurationParser.cpp
Using std::map as the cache was sufficient. I wanted to try some prefix/radix tree, but with this change, all the parsing time is spent elsewhere, so I didn't try it.
> Faster parsing - cache calls to `getTagForSymbolName`

- default.nix
- nix/llvm-backend.nix
- test.nix
This pull request patches `llvm-kompile-clang` during the Nix build so that it finds the right compiler at runtime without help from the user.
> Nix: Find clang at runtime automatically

- lib/codegen/CreateTerm.cpp
- lib/codegen/Decision.cpp
This fixes a regression where the llvm backend would not build on older versions of LLVM. Since Debian Buster is still the latest Debian Stable and buster-backports only has llvm 8 as its newest version of llvm, we still want to support llvm 8 for the time being. Hence, this change.
> add ifdef guard for sret change

- runtime/util/search.cpp
This is an optimization of the search algorithm from the previous PR: we only insert a state into the state list once if it otherwise appears during search multiple times. We are still not guaranteed to process each state exactly once, but it does cut down significantly on the number of states processed in some use cases, such as when modeling threads in K.
> dedupe state list during search

- lib/ast/AST.cpp
- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
- test/defn/imp.kore
There was an [issue](kframework/k#1945) where the the rule
```
rule LEFT => RIGHT requires REQUIRES ensures ENSURES
```
is translated to
```
axiom \implies(REQUIRES, \and(\equals(LEFT, RIGHT), ENSURES))
```
so that if ENSURES is \bottom and REQUIRES is anything else, then the axiom is axiom \bottom which is unsound. Actually, we want to say
```
axiom \implies(REQUIRES, \equals(LEFT, \and(RIGHT, ENSURES)))
```
There is a [pull request](kframework/k#2061) that changes the K frontend to emit the correct KORE syntax. This commit implements the change in the KORE syntax for the llvm-backend parsers.
Fixes #417
Signed-off-by: Erik Kaneda <erik.kaneda@runtimeverification.com>
> Parser: update rules to reflect KORE syntax change for ensures

- lib/codegen/CreateTerm.cpp
If the function has no instructions aside from the return statement, it was previously impossible to break on that function. This prevented us from breaking when a rule was applied whose right hand side was an llvm constant like `true`. This should fix this by adding the location information to the `ret` instruction.
> fix bug involving debug locations

- bin/llvm-kompile-clang
This ought to fix the LLVM backend on MacOS Big Sur when the user requests search in the K frontend via --enable-search. This was broken because the llvm@12 package doesn't build /usr/local/include as a search path for the include directories anymore.
> fix mac os llvm backend big sur --enable-search

- .gitignore
- INSTALL.md
This documentation mirrors the instructions for Ubuntu 20.04 that are
also given in `INSTALL.md`. The environment is configured using the
system package manager (rather than Nix, as is the case in the CI
environment).
I have verified the instructions on a clean VM install of macos 11, as
well as my own development system.
Running the unit tests via `./ciscript` creates DWARF symbol files
(`.dSYM`) on macos; this PR adds these to the git ignore list.
> Add documentation for local macOS builds

- matching/pom.xml
This fixes a relatively simple bug where building the llvm backend scala code as part of the k frontend maven reactor would not correctly pick up the parent pom. This can lead to version sync issues if the parent pom is changed in the frontend.
> maven relative path

- .clang-format
- include/kllvm/codegen/CreateTerm.h
- lib/codegen/CreateTerm.cpp
- runtime/io/io.cpp
- tools/llvm-kompile-codegen/main.cpp
- unittests/runtime-io/io.cpp
This PR implements the feature suggested in [this issue](https://github.com/kframework/k/issues/1889) - that the LLVM backend should be able to provide a hooked function that returns the current `*-kompiled` directory.
The necessary information is already passed through from the command line to the LLVM backend in debug mode, so the implementation just reads the baked-in symbol and constructs a boxed K string object to return. The hook is tested with a unit test in the backend using a mocked symbol.
On the frontend side, I'll implement a matching PR that adds an appropriate function symbol to the `K-REFLECTION` module, along with an integration test.
> Add hook for kompiled directory metadata

- runtime/arithmetic/float.cpp
- unittests/runtime-arithmetic/floattest.cpp
This is provided by the MPFR library similarly to ceil and floor, and is
a useful function to expose for the C semantics, where some rules are
specified in terms of floating-point truncation.
Test follow the same structure as the ceil / float tests.
This PR will be followed by a matching one on the frontend to expose the hooked function as a K rule.
> Implement floating point truncation hook

- .github/workflows/clang-format-check.yml
This PR sets up a new Github action that checks (read-only) whether each PR satisfies the clang-format style we adopted in #430. It will error if the code is formatted incorrectly.
> Add CI hook to enforce clang-format

- lib/ast/AST.cpp
- test/unparse/subst/subst.cfg.kore.out
This makes sure that the whole content of the collection is sorted when
pretty-printing, avoiding bugs where test case outputs are reordered in
the frontend test suite.
> Recurse into sub-collections when sorting

- include/kllvm/codegen/Util.h
- include/runtime/alloc.h
- include/runtime/collect.h
- include/runtime/header.h
- lib/codegen/CreateTerm.cpp
- lib/codegen/Decision.cpp
- lib/codegen/Util.cpp
- lib/llvm/EmitGCLayoutInfo.cpp
- runtime/alloc/alloc.cpp
- runtime/alloc/arena.cpp
- runtime/collect/StackMapParser.cpp
- runtime/collect/collect.cpp
- runtime/take_steps.ll
- runtime/util/ConfigurationParser.cpp
- unittests/runtime-collections/lists.cpp
- unittests/runtime-ffi/ffi.cpp
- unittests/runtime-io/io.cpp
- unittests/runtime-strings/stringtest.cpp
We add a call to koreCollect in `arenaAlloc` if we are close to running out of free space, and only allocate a new block if we're still out of space after the collection. We also modify the behavior of the alwaysgcspace so that it is cleared after each rewrite step.
This ought to ensure that there is never a long period of time where collection cannot occur, since collection can occur during any allocation with the exception of some allocations from inside hooks. It also makes it much less likely that the application will allocate more blocks than are strictly needed, thus reducing memory usage. Additionally, since we are no longer periodically making an expensive check about whether or not to perform a collection, there is a slight improvement in runtime performance.
Limitations: we …
> Enable collection during allocation

- .github/workflows/test.yml
- .github/workflows/update.yml
This PR pins the Nix version to 2.3.16 and bumps the action runner dependencies.
> Address Nix CI failures

- matching/pom.xml
- nix/llvm-backend-matching.mavenix.lock
This updates to follow the deployment of a new version of MPFR; see https://github.com/kframework/mpfr-java/pull/16.
@dwightguth I've remade this PR to get around the Nix problems with the minimum amount of effort.
> Bump MPFR version

- CMakeLists.txt
- matching/pom.xml
- nix/llvm-backend-matching.mavenix.lock
We experienced a [packaging failure](https://office.runtimeverification.com/jenkins/blue/rest/organizations/jenkins/pipelines/K/branches/release/runs/153/nodes/51/steps/104/log/?start=0) on macOS that was caused by `brew --prefix` failing during CMake.
To fix this, check for the `$PREFIX` environment variable before trying to run `brew`. This variable [is set](https://github.com/kframework/homebrew-k/blob/ba124232d8d2a0e97668960119e8292f5f713524/Formula/kframework.rb#L28) in the Homebrew formula we use, so should get picked up appropriately during packaging.
Minor: also fixes a version bump of MPFR 1.2 -> 1.4; only the Java code was missed, which is identical across these versions so there should be no impact from this other than consistency.
> Check $PREFIX before running brew

- CMakeLists.txt
Upgrading CMake caused it to begin rejecting this (admittedly incorrect) syntax, where it was accepted before.
> Minor CMake syntax error

- CMakeLists.txt
Matches https://github.com/kframework/homebrew-k/pull/10 in the Homebrew formula.
My previous change made a silly error and didn't pick up the correct prefix variable; this change should fix that and get the actual homebrew root (`/usr/local` rather than `/usr/local/Cellar/kframework/5.1.246`, say).
> Pick up the correct environment variable

- lib/codegen/CreateTerm.cpp
- lib/codegen/Decision.cpp
- lib/codegen/EmitConfigParser.cpp
This pull request contains changes to address LLVM's eventual deprecation of the use of PointerType::getElementType and Type::getPointerElementType. This set of changes is a first attempt to removing uses of these API's that are relatively straight forward to replace.
> Replace uses of getPointerElementType used as convenience

- include/kllvm/codegen/Decision.h
- lib/codegen/Decision.cpp
- runtime/util/search.cpp
This PR cherry-picks a change from the `new-gc` branch by hand to fix a crash with LLVM `--search` on Apple Silicon.
I'm not exactly sure what the cause of this bug is, but I suspect that it's some kind of subtle issue with the interaction between generated LLVM and the C code in the runtime library. The ["packed traversals" fix](https://github.com/kframework/llvm-backend/pull/446) from a while ago was a similar-looking issue.
Pulling in this change (that reduces the amount and complexity of generated code used) fixes the problem, and given that we were planning to make this change anyway I'm inclined to say that it's the most sensible solution.
I can investigate in more detail, but I'm not sure that's a worthwhile use of time given that this is a) only on Apple Silicon and b) fixed …
> Fix for crash on Apple Silicon

- runtime/util/search.cpp
As discussed, this is the fix for #461 that promotes the `states_set` variable to a global so that it can be collected in the same way as `states`.
> Collect `states_set` alongside `states` in search

- CMakeLists.txt
- ciscript
- nix/llvm-backend.nix
- unittests/CMakeLists.txt
CMake has built-in support for unit test frameworks; this PR rewrites the unit testing build script to use this support more idiomatically. The changes are:
* Instead of excluding unit-test targets from the default build target, the inclusion of the unit tests subdirectory is gated behind the CMake configuration variable `BUILD_TESTS`. If the option is enabled, `make` will build the unit tests as well as the backend itself.
* Rather than manually tracking dependencies between a phony `run-unittests` target and the individual executables, use `add_test` to get CMake to do it for us.
* Update the CI script to use the new invocations.
> Make unit testing more idiomatic

- Jenkinsfile
We currently don't test on arch linux, but it was still building the arch linux dockerfile, which can lead to build failures if the build times out due to the dockerfile taking a long time to build. Thus, I choose to disable the tests at the level of Jenkins rather than from within the bash script. this ought to mean that the dockerfile isn't build, thus fixing the timeouts.
> better way to disable arch linux build

- lib/ast/AST.cpp
- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
- test/defn/non-exec.kore
- test/input/non-exec.in
- test/output/non-exec.out.diff
The `[non-executable]` attribute specifies that a rule should not apply for rewriting in the backend.
This PR uses the existing mechanism for ignoring axioms, and so does not require specific frontend support. The test added is compiled from the following K definition:
```
module EXAMPLE
imports INT
syntax Int ::= f(Int) [function]
rule f(X) => X +Int 1 [priority(1),non-executable]
rule f(X) => X +Int 100 [priority(199)]
endmodule
```
It runs the program `f(3)`, and verifies that the output is `103` (rather than `4`, which would have been the case previously). I will add more detailed tests in the frontend when merging this update.
> Add support for `[non-executable]` attribute

- runtime/main/main.ll
- runtime/main/search.cpp
Currently, compiled interpreters set the `@statistics` global option if `argc != 4` (i.e. there is a 4th positional argument supplied to the interpreter).
At some point we'll need to add a flag to interpreters that causes them to emit binary output rather than textual KORE; doing so will need a slightly more sophisticated argument parsing implementation than the above.
This PR does the initial generalisation work towards this, and should hopefully highlight any potential issues before we add additional flags.
The proposed new behaviour is to silently ignore any unknown flags; this will break anyone using the statistics option by passing a flag other than `--statistics` (which `krun` does when invoking the interpreter), so it's worth testing this PR carefully.
Adding new flags to the …
> Generalise argument parsing in interpreters

- runtime/main/main.ll
- runtime/main/search.cpp
The tests in this repo don't exercise `--search` - this is a small change to fix a breakage identified in the K pl-tutorial tests.
> Fix for `--search` flag

- bin/llvm-krun
This is a partial fix for the C semantics linking problems. Instead of storing file contents directly in a variable, we change the logic to read from the file on disk instead.
~~Testing this will probably need to be done in the frontend so that a definition is available for `llvm-krun`; I'll do so in a separate PR before this can be merged. Informally, the C semantics test suite (which makes heavy use of `llvm-krun`) passes when built with this change.~~
This can be reviewed now, but should only be merged once https://github.com/runtimeverification/k/pull/2459 has been merged; any breakages should be caught by the backend submodule update.
> Don't `cat` huge files in `llvm-krun`

- bin/llvm-kompile
- lib/llvm/CMakeLists.txt
- lib/llvm/NoOmitFramePointerForTailcc.cpp
This PR adds the `"frame-pointer"="all"` attribute to all functions with the `tailcc` calling convention. This is a workaround to avoid a bug in LLVM 13 related to incorrect unwind info generation for such functions: https://github.com/llvm/llvm-project/issues/52758
> frame pointer workaround

- include/kllvm/binary/deserializer.h
- include/kllvm/binary/version.h
- lib/binary/serializer.cpp
- runtime/util/ConfigurationParser.cpp
Fixes #499 - simple rename of major, minor etc. so as not to conflict with the stdlib.
> Rename clashing IDs

- bin/llvm-krun
If you run `llvm-krun --dry-run --binary-input` or `llvm-krun --dry-run --binary-output`, it will not respect the presence or absence of the `--binary-output` flag because it is copying the input file verbatim to the output. In this case, we want the script to run `kore-convert` on the input file before providing it back to the user. This PR implements this change.
> run kore-convert if needed in llvm-krun --dry-run

- runtime/collections/maps.cpp
This PR makes some very small changes to the error messages we print from the hooked map functions; the messages make it slightly easier for users to understand where a crash is coming from.
Fixes https://github.com/runtimeverification/k/issues/2565
> Make error messages friendlier

- Dockerfile.arch
- Jenkinsfile
- ciscript
This PR installs python 3 explicitly, and increases the stack size available for release builds in the CI script - these seem to be the only changes needed to get the backend building on Arch again.
I've also made the OS build matrix parallel given we'll be running 3x as many of them once Jammy support (#517) is merged as well.
> Re-enable arch CI

- include/runtime/header.h
- runtime/collections/maps.cpp
- runtime/collections/sets.cpp
This PR applies a minor renaming to these variables to avoid a clash with typedefs elsewhere in the file; the clash causes an error on some compiler versions.
> Rename map, set to avoid clashes with typedefs

- Dockerfile
The llvm-backend master build timed out, but it's hard to tell exactly why this happened because the log was being spammed with progress bar updates to maven downloads. We pass -B to mvn in the dockerfile now so that it will not do this and the log will be more readable.
> use maven batch mode so we don't spam stdout

- .github/workflows/clang-format-check.yml
- include/kllvm/ast/AST.h
- include/kllvm/codegen/Debug.h
- lib/ast/AST.cpp
- lib/codegen/Debug.cpp
- tools/kore-expand-macros/main.cpp
This provides a slight speedup for `kore-expand-macros` on inputs where there are macros in the definition, but none are used in the input term.
My intuition is that the unordered map is a better fit given that we don't ever actually modify the sets of attributes that AST nodes have, but do a lot of `count` lookups to see if an attribute is present; with an ordered map this is guaranteed `O(log n)` but with an unordered one it's average `O(1)`.
There are a couple of other small changes:
* Upgrade the version of the clang-format action we use; the old one was breaking
* Prevent any recursive building of terms when there are no macros present in the definition.
> Use `unordered_map` to store attributes

- lib/codegen/Debug.cpp
Fixes https://github.com/runtimeverification/k/issues/2637.
The actual change here is pretty small - it adds some extra global flags to the debug metadata we emit to match the behaviour of clang when emitting DWARF v5 files.
> Fix GDB on Ubuntu Jammy

- .github/workflows/test-flake.yml
- .github/workflows/test.yml
- bindings/python/package/poetry.lock
- flake.lock
- flake.nix
- nix/overlay.nix
This PR makes sure that we include `pybind11` as a pseudo-submodule in the same way as we do for immer and rapidjson. It also adds the flake build as a step in the nix testing workflow.
> Build LLVM backend Python bindings in flake

- bindings/python/CMakeLists.txt
- bindings/python/ast.cpp
- bindings/python/runtime.cpp
This PR makes a small change to how we build the Python bindings; it allows the Type 1 and Type 2 components (#544) to be split when they are both implemented. There is no actual change to the Type 1 binding already being tested in K as a result of this PR..
> Split Type 1 / Type 2 bindings

- bindings/python/CMakeLists.txt
This prevents the bindings from ending up at `/usr/lib/python` when the K package is built and installed. Will be followed by a frontend PR to install the bindings with `pip` as we currently do for Pyk.
> Install Python bindings outside of `lib/`

- matching/src/main/scala/org/kframework/backend/llvm/matching/Matching.scala
IntelliJ pointed out that these two lines are not used.
> Remove dead code.

- bin/llvm-kompilex
This code path is exercised directly (as far as I know) only in the C semantics, and so previous testing didn't identify a bug whereby the two-argument case isn't accepted.
The code change here is small, and you can see that the documentation in the script already indicates that two positional arguments should be valid.
> Fix argument count check for `object.o` case in `llvm-kompile`

- include/runtime/header.h
- runtime/strings/CMakeLists.txt
- runtime/strings/strings.cpp
- runtime/util/CMakeLists.txt
- runtime/util/util.cpp
- test/defn/strip_injection.kore
- test/input/strip_injection.in
- test/output/strip_injection.out.diff
- unittests/runtime-ffi/ffi.cpp
- unittests/runtime-io/io.cpp
- unittests/runtime-strings/stringtest.cpp
This hook throws an error if the term it is passed is not directly a token; this PR allows it to strip off a single layer of injection.
Fixes https://github.com/runtimeverification/k/issues/1038 - the test case added here is directly derived from the module in that issue.
> Strip injection in `token2string`

- nix/llvm-backend.nix
Currently, when trying to compile with the search functionality via nix, we fail with the following error:
```bash
kompile --enable-search --md-selector 'k&!noio' --no-exc-wrap --backend llvm  simple-untyped.md -d .
In file included from /nix/store/p4jsvspx6w81j706rcl10pia6zdfc4la-k-5.5.8-dirty-maven/lib/kframework/../../bin/../lib/kllvm//llvm/main/search.cpp:4:
/nix/store/p4jsvspx6w81j706rcl10pia6zdfc4la-k-5.5.8-dirty-maven/lib/kframework/../../bin/../include/kllvm/runtime/header.h:8:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
^~~~~~~
1 error generated.
[Error] Critical: llvm-kompile returned nonzero exit code: 1
```
This is because we do not include the `gmp.h`/`mpfr.h` headers found in the `gmp.dev`/`mpfr.dev` nix packages
> Add missing headers when running llvm-kompile with the search flag

- bin/llvm-kompile
- bindings/python/CMakeLists.txt
- nix/overlay.nix
- test/lit.cfg.py
Installing the bindings under a non-standard path (which we only used temporarily previously) was going to make it much harder to fix the debian packaging script for K; this PR puts them under `lib/kllvm` instead.
> Change bindings install path

- include/runtime/header.h
- runtime/arithmetic/float.cpp
- runtime/arithmetic/int.cpp
- runtime/collections/lists.cpp
- runtime/collections/maps.cpp
- runtime/collections/sets.cpp
- runtime/io/io.cpp
- runtime/meta/ffi.cpp
- runtime/strings/bytes.cpp
- runtime/strings/strings.cpp
This PR adds a generic identifier to every exception thrown by hooked function symbols in the LLVM backend.
The new output looks like this:
```
terminate called after throwing an instance of 'std::invalid_argument'
what():  [hook_STRING_string2base_long]: Not a valid integer
```
Note that the exact hook name printed each time may not precisely match the source of the error (because some hooks are implemented in terms of each other - e.g. `int2string` in terms of `base2string`), but this change will at least make it slightly easier to track down what the problem is.
Closes #593
> Better error messages from hooks

- runtime/strings/strings.cpp
The `sprintf` function is deprecated on macOS, so we replace it with a straightforward use of `snprintf` using the size of the stack buffer.
Fixes #589
> Migrate use of `sprintf`

- .github/workflows/test-flake.yml
This stops the logs from being tailed to their last 10 lines, making issues in CI easier to debug.
> Print build logs when building Nix flakes

- bin/llvm-krun
The recent ubuntu update to CI runners has updated shellcheck, which includes this new check for unreachable code. Our usage is indirect via signal trapping, and so we can safely ignore it.
> Hotfix for shellcheck breaking

- bin/llvm-kompile
- bin/llvm-kompile-clang
This reverts commit 791487a8c9196d8093f4c06aa60ad201847fc2b5.
This is a temporary fix to get the KPlutus K update job to go through; we will want to reinstate some form of this change later when we better understand what's going on.
> Revert "Use opaque pointers when they're available (#586)"

- .github/workflows/update.yml
[This dependency update PR](https://github.com/runtimeverification/llvm-backend/pull/615) demonstrates that the current Nix / Maven CI scripts are broken if something actually changes in the Maven dependencies, because the workflow is not configured to authenticate as the RV-Jenkins user when it tries to commit.
This PR changes the workflow to reflect what K does in the [equivalent workflow](https://github.com/runtimeverification/k/blob/master/.github/workflows/update-deps.yml).
> Fix Nix / maven Github job

- .github/workflows/update.yml
This ports in the equivalent change from the K repo; we don't need to be spending lots of time updating the maven dependencies unless we need to.
> Don't run maven update job if we don't need to

- bindings/c/include/kllvm-c/kllvm-c.h
- bindings/c/lib.cpp
- test/c/Inputs/kitem.c
- test/c/test_kitem.kore
We don't want to inject terms that are already of sort `KItem` into `KItem` again; doing so crashes the interpreter. This PR checks if the sort passed to `kore_simplify` is `SortKItem`, and if it is, doesn't construct an injection.
The PR also includes a test that exercises this code.
Fixes #622
> Handle simplifications in `SortKItem`

- include/kllvm/ast/AST.h
This header was being pulled in transitively before somehow, which causes a build failure on macOS because the structure of the upstream headers changed and `<set>` was no longer available.
> Include `<set>` in AST.h

- matching/src/main/scala/org/kframework/backend/llvm/matching/Matching.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
Makes a few functions public and changes the signature of parseTopAxioms and parseFunctionAxioms to make them easier to use. These refactorings make it easier to use this code in another backend I am working on.
> some minor refactorings of pattern matching code

- bindings/c/include/kllvm-c/kllvm-c.h
- bindings/c/lib.cpp
- test/c/Inputs/bytes.c
- test/c/test_bytes.kore
This PR exposes new C API functions for creating KORE string patterns and tokens (`\dv{Sort}{"..."}`); the new functions accept a _length_ as well as the string data to be used for the token value. This means that tokens that contain null bytes can be constructed; previously, the construction of a `std::string` would truncate them.
The test for this change is similar to the other C bindings tests.
Closes #629
> Expose length parameter for tokens

- nix/llvm-backend.nix
The new fmt dependency was missing from the set of propagated build inputs for the backend; this PR adds it to that set.
> Propagate `fmt` as a build input to consumers

- bindings/c/include/kllvm-c/kllvm-c.h
- bindings/c/lib.cpp
- test/c/Inputs/simplify.c
This is a small change that exposes the backend's "free all runtime memory" function to the C bindings. It can safely be called at the end of an RPC request to make sure that no memory is hanging around after the request finishes (leaks).
A call to the function is added to the simplification test.
Fixes #636
> Expose 'free all' function to C bindings

- tools/kore-expand-macros/main.cpp
The list of includes for this tool was insufficient, which broke the Arch linux release job when a transitive include changed in a rolling package.
This PR makes the list of required includes explicit.
Fixes https://github.com/runtimeverification/llvm-backend/issues/645
> Fix includes for `kore-expand-macros`

- flake.lock
- flake.nix
- nix/overlay.nix
This PR updates Nixpkgs so that we can get `llvmPackages_15`, and bumps our integration tests to run on 15 rather than 14 (while still building on 11-15).
There is one hack added (to compile with Clang 14 / LLVM 15 on macOS) because `libcxx` is still a bit broken in LLVM 15; I'll revisit this down the line when the Nixpkgs version is more stable.
> Build on LLVM 15

- test/c/test_bytes.kore
This missing escape causes the test to break in some shells but not others, hence it not being picked up previously.
> Missing escape sequence in test

- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
This doesn't actually affect the llvm backend because the llvm backend never actually processes the decision trees generated for hooked symbols, but if we don't filter out these axioms, then the maude backend will generate the following axioms:
```
rule L:List .List => L
rule .List L:List => L
```
which will not terminate since maude performs ACUI matching.
> filter out unit axioms

- bindings/c/include/kllvm-c/kllvm-c.h
- bindings/c/lib.cpp
- include/runtime/header.h
- runtime/util/ConfigurationParser.cpp
- test/c/Inputs/binary_simplify.c
- test/c/test_binary_simplify.kore
This PR adds a new function `kore_simplify_binary`, which avoids constructing a C++ AST at all (instead, it directly constructs a runtime term from the binary data and performs simplification).
The test for the PR is similar to previous bindings tests.
> Binary simplification API

- matching/src/main/scala/org/kframework/backend/llvm/matching/Matching.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
This is another change that doesn't affect the LLVM backend directly but exposes some functionality to the Maude backend which consumes the scala code in this module as a library.
What this change does is add a boolean flag to `parseFunctionAxioms` which specifies whether the function should keep simplification rules or discard them. When set to true, simplification rules are kept and not discarded. The default value the llvm backend uses is false, which is the previous behavior.
In order for this to work, we also have to add the pattern match cases for the structure of simplification rules to the pattern match case present in the code that destructures axioms, otherwise, we will silently discard these rules.
> add flag to parseFunctionAxioms to keep simplification rules

- include/kllvm/hello/hello.h
This simple PR deletes the hello directory and the hello.h from the include/kllvm include directory.
This folder and file were included at the begging of the project and today isn't used by or as a dependency for any other file, so it's safe to delete them.
Same as #662
> Cleanup old directory

- bin/llvm-kompile
- debug/kgdb.py
Some recent changes to the backend had caused the GDB scripts to drift:
* The new `llvm-kompile` script wasn't setting the debug `1` flag for codegen properly.
* Because `step` is a function somewhere in `libc`, we had to rename our step function to `k_step` to support dynamic loading. The GDB script didn't reflect that.
Fixes #661
> Fix `-g` flag propagation

- bin/llvm-kompile
- bin/llvm-kompile-clang
- test/python/test_construct.py
- test/python/test_steps.py
Related to https://github.com/runtimeverification/k/issues/3165, https://github.com/runtimeverification/k/pull/3171
The Python bindings build process chooses an output filename by running the Python configuration module, rather than having one passed through the kompilation pipeline. This means that we need to special-case the handling of relative output paths in a couple of places when generating Python modules:
* Setting the output directory for Python modules rather than automatically dumping them in the CWD. This directory defaults to the parent of the `definition.kore` argument to `llvm-kompile`.
* Allowing this directory to be overridden when running the Nix test suite, which separates input definitions and the generated modules.
`llvm-kompile ... python[ast]` has not had its …
> Make python output relative

- lib/parser/KOREParser.cpp
This fixes two warnings-as-errors experienced by a Nethermind developer on:
> ubuntu 22.04.1 with clang12.0.1-19ubuntu3
I'm not sure why this doesn't happen in CI, but there is no harm in fixing the issues:
* Explicitly make a loop variable unsigned
* Add a default-case abort to a switch; we do this elsewhere to generate unreachable code, and error-handling elsewhere in the parser will catch bad tokens
> Fix compiler warnings

- nix/llvm-backend.nix
Fixes #668 - the underlying issue is that the binary section we embed the Python script into is stripped by default when built under Nix. This PR leaves debug information in the backend libraries, which is a more general solution in any case.
> Don't strip LLVM backend libraries

- CMakeLists.txt
- tools/kore-arity/CMakeLists.txt
- tools/kore-convert/CMakeLists.txt
- tools/kore-strip/CMakeLists.txt
- tools/llvm-kompile-codegen/CMakeLists.txt
- unittests/compiler/CMakeLists.txt
We were relying on a [somewhat outdated CMake command](https://bugzilla.opensuse.org/show_bug.cgi?id=1096168#c2) to identify the LLVM libraries we need to link against.
This PR replaces uses of `map_llvm_components_to_libnames` with the more up-to-date `llvm_config` macro.
> Fix llvm build on Arch

- tools/kore-arity/main.cpp
- tools/kore-convert/main.cpp
- tools/kore-strip/main.cpp
- tools/kprint/main.cpp
This PR fixes two issues with one stone:
* For some reason, accessing the registered options to hide `--color` in `kprint` causes a segfault when running the backend on arm64/macOS Nix, when it's built as part of K. I noticed because it was breaking the submodule update, but I can reproduce this locally.
* We get a lot of LLVM options from `--help` for the LLVM backend tools; we can give our options an explicit category and hide the rest.
I have verified locally that these changes will allow the K submodule update to go through.
> Improve hiding of LLVM options

- lib/ast/AST.cpp
- matching/src/main/scala/org/kframework/backend/llvm/matching/Generator.scala
Fixes: #667 
Create support for the `[total]` attribute to replace `[functional]` in the future.
> Add support to `total` like `functional`

- docs/binary-kore.md
Addresses a typo in the binary KORE documentation:
```
0x56 == 'V'
0x78 == 'w'
```
> Correct typo in binary docs

- bin/llvm-kompile-testing
In this PR, I propose the following modifications:
- Get the full path of the definition file: The idea is to enable the use of `llvm-kompile-testing` from any directory without the need to pass the absolute path of a file.
- Renaming variable `main` to `mode`: The idea is to make this variable naming more meaningful as we have different modes to generate the interpreter besides the `main` one.
> Update flags definition and naming of `llvm-kompile-testing`

- include/runtime/header.h
- runtime/main/search.cpp
- runtime/util/ConfigurationSerializer.cpp
- test/lit.cfg.py
- test/search/search.kore
Fixes #690 
This PR enables the interpreter created with search support to print the file using the KORE binary.
> Add support to `--binary-output` on search interpreter

- include/kllvm/printer/printer.h
- lib/printer/printer.cpp
- test/unparse/exp/exp2kore.cfg.kore
- test/unparse/exp/exp2kore.cfg.kore.out
- tools/kprint/main.cpp
Fixes https://github.com/runtimeverification/llvm-backend/issues/693; this issue is a feature request to get access to the post-processed KORE that `kprint` currently uses to produce pretty surface syntax.
> Output processed KORE from `kprint`

- bin/llvm-kompile-clang
Currently, we require callers of `kompile` to know their platform's shared library extension (and invoke the K tools accordingly). It would be convenient to add the correct extension for them automatically when compiling in C mode.
The positive case of this change is not yet used by any code (https://github.com/runtimeverification/k/pull/3259 and related K as a library work will eventually integration test it), and I'm confident that the existing test suite will catch any inadvertent breakages caused by the PR.
> Infer shared library extension in `c` mode

- nix/llvm-backend.nix
This is a small fix to ensure we don't leak out and call the wrong `uname` in Nix builds. Related to changes made in https://github.com/runtimeverification/llvm-backend/pull/711
> Call uname from Nix properly

- bin/llvm-kompile-clang
- test/c/test_infer_ext.kore
@jberthold identified this bug to me; as previously written the regex would give you false positives. Also realised I can add a test for this feature reasonably easily; have done so to avoid future errors of this type https://www.gnu.org/software/bash/manual/bash.html#index-_005b_005b
> Fix quoting of shell regex

- bindings/c/include/kllvm-c/kllvm-c.h
- bindings/c/lib.cpp
- test/c/Inputs/parse.c
- test/c/test_parse.kore
Previously, the only way to construct a KORE pattern from the C bindings was to build it by hand. This PR exposes and tests the KORE parser to the bindings.
> Implement KORE parser for C bindings

- test/c/Inputs/api.c
- test/c/Inputs/api.h
- test/c/Inputs/binary_simplify.c
- test/c/Inputs/bool.c
- test/c/Inputs/bytes.c
- test/c/Inputs/k.c
- test/c/Inputs/kitem.c
- test/c/Inputs/parse.c
- test/c/Inputs/simplify.c
- test/c/Inputs/steps.c
- test/c/test_binary_simplify.kore
- test/c/test_bytes.kore
- test/c/test_c.kore
- test/c/test_k.kore
- test/c/test_kitem.kore
- test/c/test_parse.kore
- test/c/test_simplify.kore
- test/c/test_steps.kore
- test/lit.cfg.py
These tests were using a lot of duplicate boilerplate code for handling `dlopen`, `dlsym` etc. This PR refactors the tests to avoid this, making them easier to write and maintain in the process.
Each test is changed only mechanically to invoke the dynamically loaded functions via the `api` shim, rather than getting the required symbols in each test by hand. The invocations made by the actual KORE test cases are changed to use a `lit.cfg.py` entry, but the tested behaviour is identical in each case.
> Improvements to C binding tests

- bin/llvm-kompile
- test/lit.cfg.py
This makes it easier to integrate the backend bindings into a larger app: if you can compile the bindings from a definition, you can then get the right include path to find `<kllvm-c/kllvm-c.h>`
> Add flag to get backend include dir from `llvm-kompile`

- .github/workflows/release.yml
This switches us from the old way (using Jenkins) to update dependents downstream, to the new way using the GH Runner job in devops repo.
> Switch to new GH Runner based deps updater

- bindings/python/runtime.cpp
Closes #724
This PR fixes an issue where `InternalTerm.__str__` returns one of the strings used in the runtime directly, rather than constructing an `std::string` of the appropriate length, leading to it reading off the end and causing the issue in #724 
Unfortunately, the script in #724 no longer triggers the issue when converted to an LLVM backend test, likely due to slight differences in how the libraries are compiled, so I am submitting without a test for now. I'll open a separate PR to add a test to Pyk instead.
> Fixed InternalTerm.__str__ binding so that it doesn't assume null-teminated string

- include/kllvm/codegen/Debug.h
- lib/codegen/CreateTerm.cpp
- lib/codegen/Debug.cpp
- lib/codegen/EmitConfigParser.cpp
These methods are removed in LLVM 16; this PR migrates usages to more appropriate ones.
> Migrate uses of deprecated APIs

- bin/llvm-kompile-testing
Add options already supported by `llvm-testing`:
- `library`: generate an interpreter with no main function linked.
- `pythonast`: build a Python bindings module for the KORE AST structures only, without relying on a specific K definition.
- `c`: build a C bindings module rather than a standalone executable.
> Update llvm-kompile-testing usage

- bindings/python/ast.cpp
- include/kllvm/ast/AST.h
- test/python/test_patterns.py
- test/python/test_sorts.py
- test/python/test_symbols.py
This PR adds some missing bindings to the Python AST module to facilitate a conversion <-> the Pyk AST types. Lightweight tests are added for the new features.
Fixes https://github.com/runtimeverification/llvm-backend/issues/736
> Add missing structural features to AST module

- lib/codegen/CMakeLists.txt
- lib/codegen/DecisionParser.cpp
- matching/src/main/scala/org/kframework/backend/llvm/matching/dt/DecisionTree.scala
- test/defn/test-unicode.kore
Previously, the decision tree YAML file was encoded based on the system locale, but `libyaml` would always try to read it as UTF-8 regardless. This caused segfaults on some systems, particularly due to `lit` setting the locale to `POSIX` in the testing environment.
This PR addresses this by explicitly setting the YAML file encoding to UTF-8 and adding error checking in case the read fails.
> Enforce UTF-8 for decision tree YAML

- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
This case corresponds to rules with no explicit side condition where the order of arguments has been swapped to support the new-format [no-antileft rewrites](https://github.com/runtimeverification/k/pull/3314).
The original change to support these rules added the corresponding case for rules _with_ side conditions, and the line added here was missing.
I will add a test to the frontend for this change while https://github.com/runtimeverification/llvm-backend/pull/745 is still in flight; once that is merged I will add the same test to the backend suite.
Fixes https://github.com/runtimeverification/llvm-backend/issues/747; I have confirmed by running the C semantics test suite with the new-format rewrites.
> Add missing case to pattern matching for new-format rules

- lib/ast/AST.cpp
This simple PR deletes the map of `Hyph` to `-` as the K frontend doesn't produce this token anymore, so the llvm backend doesn't need to translate it anymore.
> Delete `Hyph` translation as it's not part of KORE Syntax anymore

- runtime/main/search.cpp
- runtime/util/search.cpp
- test/input/search-execute-to-branch.in
- test/output/search-execute-to-branch.out.diff
- test/search/k-files/search-execute-to-branch.k
- test/search/search-execute-to-branch.kore
This PR introduces a new feature to the llvm-backend: the option to stop the search execution when a branch is found.
This feature is already supported by the Haskell-backend `kore-exec` within the flange  `--execute-to-branch`. The name and the use of the flag are the same used on Haskell-backend to ease the adoption by users.
To use it: 
```
module TEST
imports BOOL
syntax Foo ::= "a" | "b" | "c" | "d" | "e"
rule a => b
rule b => c
rule c => d
rule c => e
endmodule
```
```Bash
kompile --backend llvm --enable-search test.k
krun -cPGM='a' --search --execute-to-branch 
```
Expected output:
```
{
Result:GeneratedTopCell
#Equals
<k>
c ~> .
</k>
}
```
Fixes #752
> Introducing llvm backend support for `--execute-to-branch` feature

- bindings/c/include/kllvm-c/kllvm-c.h
- bindings/c/lib.cpp
- bindings/python/ast.cpp
- include/kllvm/ast/AST.h
- lib/ast/AST.cpp
- test/c/Inputs/api.c
- test/c/Inputs/api.h
- test/c/Inputs/remove_assoc.c
- test/c/k-files/remove_assoc.k
- test/c/test_remove_assoc.kore
This has historically been handled by the KORE parser, but it would be useful for Pyk and the C bindings to be able to desugar _programmatically-constructed_ input.
In this PR, a new `desugarAssociative` method is added to the KORE Pattern AST hierarchy; this method expands associative syntax sugar into nested calls using the same logic as the parser (except that the parser will not recurse into subterms when doing so).
Testing of the method is done through the C bindings, which programatically construct a term with a `\left-assoc` symbol, desugar it, then evaluate it. No explicit python test is added as it's awkward to construct these terms without going through the parser; Pyk tests of this feature + the C bindings test will be sufficient coverage.
Fixes: …
> Desugar `\{left,right}-assoc`

- bin/llvm-krun
Fixes #754 
A simple PR  to improve the `--verbose` use on `llvm-krun` by outputting more steps of the execution process!
> Reorganizing `set -x` calls for verbose execution

- lib/ast/AST.cpp
The bug here fixes an issue where the _first_ subterm would not be recursively desugared as it's not iterated over inside the loop. Passes the tests added to https://github.com/runtimeverification/pyk/pull/435.
> Add missing recursion case

- test/lit.cfg.py
The previous way of writing this test stanza would allow for a single input to these definitions to fail, while reporting that the test itself was passing overall.
This PR refactors the test to ensure that failures are properly reported. I have inspected and validated that:
* No tests were silently failing as a result of the old code.
* A test that I would expect to fail does fail with the new directive, when it would have silently passed before.
Fixes https://github.com/runtimeverification/llvm-backend/issues/768
> Fix broken test mechanism

- bindings/c/lib.cpp
- test/c/Inputs/remove_assoc.c
While debugging https://github.com/runtimeverification/llvm-backend/issues/770, I found a few small memory leaks in the C bindings and associated tests. This PR cleans up places where we were not properly freeing temporary objects.
The fixes are unrelated to the Python bindings, but allow me to check that nothing obvious is being leaked by the underlying associative desugaring code.
> Fix minor memory leaks

- runtime/strings/bytes.cpp
Fixes #771 
This simple PR modifies the `get_ui` function to `get_ui_named` while keeping its interface the same as the previous one. The new function receives a string representing the name of the caller function that will be used to improve the error message if the integer has an overflow!
> Improving `get_ui` error message

- docs/binary-kore.md
- include/kllvm/binary/deserializer.h
- test/binary/variable_1.kore
- test/binary/variable_2.kore
There was a missing case in the binary deserializer that meant we couldn't deserialize pattern variables (`X : Sort`) properly. This PR implements, tests and documents the missing case.
No change to the format version is required as the serializer was already handling this case properly, and all existing files that were previously valid remain so.
Fixes #779
> Deserialize pattern variables correctly

- nix/llvm-backend.nix
This is a hotfix for a compilation issue being experienced by @tothtamas28; I will endeavour to fix this properly in a separate change.
Related: https://github.com/runtimeverification/llvm-backend/issues/783
> Fix drifting line in nix script

- include/runtime/alloc.h
- include/runtime/header.h
- runtime/util/util.cpp
While working on a minimal hook implementation, I identified the following papercuts in usage of the LLVM backend:
* `size_t` is not defined when including `alloc.h`
* Users need to define their own `dotK` block-getter - this is a common enough task we should put it in the backend.
> Fix for small papercuts in hook interface

- .github/workflows/test-flake.yml
- .github/workflows/update.yml
We had to do this on K recently to avoid the "System Integrity Protection" issue in CI when installing Nix; this PR propagates the same change over to the LLVM backend.
> Bump `install-nix-action`

- unittests/runtime-ffi/ffi.cpp
- unittests/runtime-io/io.cpp
- unittests/runtime-strings/stringtest.cpp
This change adds an extra stub to the unit test implementations that require it to placate the linker.
> Stub implementation of `constructCompositePattern`

- include/runtime/header.h
- runtime/collections/hash.cpp
- runtime/collections/kelemle.cpp
- runtime/meta/substitution.cpp
- runtime/strings/bytes.cpp
- runtime/strings/strings.cpp
- runtime/util/ConfigurationParser.cpp
- runtime/util/ConfigurationPrinter.cpp
- runtime/util/ConfigurationSerializer.cpp
- unittests/runtime-io/io.cpp
As part of general work towards improving and documenting the public interface of the LLVM backend, this PR converts the existing macros used for manipulating blocks and block headers into inline functions.
Making this change has a few benefits:
* Improved debugging; it can be annoying having to paste the macro definitions into gdb / lldb when trying to evaluate expressions on values in scope.
* No macro pollution; we've run into situations previously where the runtime header needs to be included in a particular order so as not to pollute other headers' definitions.
* Easier code to read; the excess parentheses required to safely implement macros make the code tricky to read.
* Improved type safety.
The change makes the backend marginally slower to build, but the performance of the test …
> Convert `runtime.h` macros to real functions

- bin/CMakeLists.txt
- bin/llvm-kompile
- bin/llvm-kompile-clang
- bin/utils.sh
This PR makes some minor refactorings to the `llvm-kompile-*` scripts, and adds an additional profiling option that (in verbose mode) prints the time taken by each step of the compilation pipeline.
I will follow this PR up with additional profiling information in the code generator.
For a small example:
```console
$ llvm-kompile test-kompiled/definition.kore test-kompiled/dt main -v --profile
+ /home/bruce/code/llvm-backend/build/install/bin/llvm-kompile-codegen test-kompiled/definition.kore test-kompiled/dt/dt.yaml test-kompiled/dt 0
time=0.034
+ /usr/lib/llvm-14/bin/opt -mem2reg -tailcallelim -tailcallopt tmp.gsYQm9W8RC -o tmp.CTS0WVHve7
time=0.021
+ /home/bruce/code/llvm-backend/build/install/bin/llvm-kompile-clang tmp.CTS0WVHve7 main nolto -fno-stack-protector -v --profile …
```
> Add `--profile` option to `llvm-kompile`

- nix/llvm-backend.nix
In Homebrew, to get a compatible version of the date command we need to use `gdate` rather than `date`. In Nix on macOS, this isn't the case and we should patch in the unprefixed `date` command.
This is a small hotfix for the LLVM backend update job (https://github.com/runtimeverification/k/pull/3498) following #793
> Patch `gdate` in Nix

- bin/llvm-kompile
- bin/llvm-kompile-clang
- include/kllvm/codegen/CreateTerm.h
- lib/codegen/CreateTerm.cpp
- lib/codegen/Decision.cpp
- runtime/finish_rewriting.ll
- runtime/fresh.ll
- runtime/take_steps.ll
This PR replaces the LLVM `CallingConv` from `Fast` to `Tail`. By doing so, we no more need to call the `tailcallopt` optimization pass and decrease the kompilation time.
Fixes: #795
> Replacing fastcc with tailcc

- bin/llvm-kompile
- include/kllvm/codegen/ApplyPasses.h
- lib/codegen/ApplyPasses.cpp
- lib/codegen/CMakeLists.txt
- tools/llvm-kompile-codegen/main.cpp
The new profiling option for `llvm-kompile` reveals that we're spending a lot of time materialising IR to disk between the code generator, `opt` and `llc`.
We can probably shave a reasonable chunk of time by keeping the module in memory, and running passes on it directly via the LLVM API. This PR is a prototype implementation of that change.
Rough performance numbers for the `llvm-kompile` part of the C semantics:
* Before: **30s**
* After: **20s**
Eventually, in a separate change we may want to drop `llc` for the generated module as well following something like this: https://stackoverflow.com/questions/34822212/generate-machine-code-directly-via-llvm-api
> Don't materialise code for `opt`

- bin/llvm-kompile
On some shells, `"$debug"` seems to be passed as an empty string to the argument parser for `llvm-kompile-codegen`, rather than just being omitted. This PR fixes the issue and quotes the argument properly.
> Fix shell quoting

- tools/llvm-kompile-codegen/main.cpp
This is a small fix for a broken submodule job: https://github.com/runtimeverification/k/actions/runs/5534103289/jobs/10098638343?pr=3508
The issue is that on some platforms (macOS / arm64), the optimisation passes we run inline with the code generator require some target information to be initialised; this PR performs the necessary initialisation in `llvm-kompile-codegen`.
See https://github.com/llvm-hs/llvm-hs/issues/250 for similar issues faced by other projects, with the same solution.
> Initialise llvm

- bin/llvm-kompile-clang
The change required here is smaller than discussed yesterday in the K meeting; the underlying issue was actually just that our build system wasn't adding a compiler flag that's required for `py::module_local()` to work properly.
Reference from the docs (different error, but contains the instruction to make sure that you're passing this flag): https://pybind11.readthedocs.io/en/stable/faq.html#someclass-declared-with-greater-visibility-than-the-type-of-its-field-someclass-member-wattributes
This PR adds that flag; I have verified that K built using this modified backend fixes my reproduction code from https://github.com/runtimeverification/pyk/issues/551
Fixes https://github.com/runtimeverification/pyk/issues/551
> Build Python bindings with `-fvisibility=hidden`

- runtime/util/ConfigurationSerializer.cpp
`serializeRangeMap` was not using the proper KORE representation for the arguments of the element function of range maps. This was leading to the serialization of configurations that included range maps to fail. This was discovered while testing with the C semantics. (joint work with @theo25)
> Bug fix in serializeRangeMap

- runtime/util/ConfigurationSerializer.cpp
There was a bug in how we were serializing string buffers and strings/byte arrays of length 0. It was assuming that such strings are null terminated when they appear in a `string *` in the kore heap, but this is not necessarily true. Similarly, it was assuming that a string buffer was null terminated, which is also not true.
It's pretty difficult to write reliable tests for this bug since it relies on garbage collection to pollute the word that gets printed with a word that does not begin with the null byte. This is impossible in our existing test harness for serialization since  we don't ever garbage collect anything in those tests. However, we know that the fix works because it fixes the regression in the Booster's integration tests that arose from introducing garbage collection calls …
> fix bugs with serializeConfiguration and garbage collection

- bindings/python/ast.cpp
- include/kllvm/ast/AST.h
- include/kllvm/codegen/Debug.h
- lib/ast/AST.cpp
- lib/codegen/Debug.cpp
Fixes #815
Create Python bindings for `KOREParser`, `KOREDefinition`, `KOREModule`, and all `KOREDeclaration` classes in order to expose the definition parser.
As part of this, 
- a few `unique_ptr`s were changed to `shared_ptr`s because pybind cannot handle anything which takes a `unique_ptr` as an argument
- fixed a bug in `KOREAxiomDeclaration` where `axiom` was always printed even when the instance was actually a `claim`
- improved `const` correctness in a few places
Tests are implemented on the Pyk side in runtimeverification/pyk#599
> Create Python bindings for definition parser

- bin/llvm-kompile-compute-loc
- bin/llvm-kompile-compute-ordinal
We were previously incorrectly assuming that all axioms in a kore file were indented exactly two spaces, which is not correct. This led to the ordinals and locations being generated being incorrect. This ought to fix that.
> fix llvm-kompile-compute-loc and llvm-kompile-compute-ordinal

- test/k-rule-find/definition.kore
- test/k-rule-find/k-files/k-rule-find-test.k
- test/output/k-rule-find/bar1-label.out.diff
- test/output/k-rule-find/bar2-label.out.diff
- test/output/k-rule-find/fooRule-label.out.diff
- test/output/k-rule-find/rule-label.out.diff
- test/output/k-rule-find/seqstrict-label.out.diff
- test/output/k-rule-find/strict2-label.out.diff
- tools/k-rule-find/main.cpp
Fixes #725
This PR updates the `k-rule-find` tool to return multiple rule labels when the given location has `cool` and `heat` rules, like when using `seqstrict` and `strict`.
This PR will break the [`context-labels`](https://github.com/runtimeverification/k/tree/master/k-distribution/tests/regression-new/context-labels) test on the K frontend as the output expected there has only one rule when more than one will be returned after this modification.
> Update `k-rule-find` to handle multiple rule labels

- bindings/c/lib.cpp
We discovered a bug in the kore_block_get_bool function. It was reading 8 bytes and then casting the result to a bool, but a block containing a boolean as a child has one byte that is determined and 7 unspecified bytes that contain padding. As a result, if the padding was nonzero, the function would return true even if the injection actually contained the boolean `false`. This should fix that bug by casting the pointer to `bool*` before reading.
> fix bug in kore_block_get_bool

- nix/llvm-backend-matching.nix
This is a small follow-up for #827
> Set stack size for JVM when Nix-wrapping LLVM matching

- bin/utils.sh
- nix/llvm-backend.nix
Fixes https://github.com/runtimeverification/k/issues/3610
This PR replaces the use of `date` and `gdate`, depending on the user system, to get the current timestamp in milliseconds with a simple `Perl` program to improve compatibility across Unix-like systems.
This modification is needed due to the following:
- `date` in MacOS is a FreeBSD version that doesn't support (return) timestamps in milliseconds as we need in `llvm-kompile --profile` introduced by #793.
- `gdate` isn't a default package nor a standalone package to be installed in MacOS. Instead, it's commonly installed with `coreutils`. We do not want to ask our users to install all `coreutils` when we only need `gdate` from it and to use it in an optional flag.
- Other options were considered as `python time` and `bash …
> Replacing date/gdate with perl program

- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
Here we add code to the scala codebase to collect into the AxiomInfo the ensures clause of axioms. This is not actually used by the llvm backend because the llvm backend does not support `ensures`, but we need to collect it because this code path is shared with the Maude backend.
> collect ensures clause in Parser.scala

- matching/pom.xml
- matching/src/main/scala/org/kframework/backend/llvm/matching/Generator.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
- nix/llvm-backend-matching.mavenix.lock
Blocked on https://github.com/runtimeverification/k/pull/3676
This PR implements the changes to the scala code in the llvm backend to support multi-ary and and or. In order to do this without the second wave of changes to the frontend, we rely on a slightly messy approach that involves breaking the abstraction barrier of the scala code in the frontend. this will be cleaned up by a later PR that will revert the first of the two commits in this PR.
> First wave of and/or changes to the llvm backend

- tools/llvm-kompile-codegen/main.cpp
This modification allows multiple `--debug` flags to be accepted by `llvm-kompile-codegen`
> Add ZeroORMore option oto debug cl::opt

- bin/llvm-krun
- nix/llvm-backend-matching.mavenix.lock
This PR introduces the `--debug-command` to the `llvm-krun` flag that enables the use of GDB and LLDB in a non-iterative mode by passing a file with the debugger commands appropriate for the OS.
This PR is part of #840 and will enable testing the debugger on the CI.
> Creating `debug-command` flag on `llvm-krun`

- .github/workflows/update.yml
- matching/pom.xml
- nix/llvm-backend-matching.mavenix.lock
Mavenix was bumping the version of snapshot dependencies every time we push to the frontend, which isn't very nice. Here we change it to only trigger the workflow if the pom changes or if we need to manually trigger it because something broke.
> trigger maven updates only manually or on changes to the POM

- include/kllvm/codegen/Decision.h
- include/runtime/header.h
- lib/codegen/Decision.cpp
- lib/codegen/DecisionParser.cpp
- runtime/util/ConfigurationPrinter.cpp
- test/k-rule-apply/definition.kore
This PR fixes https://github.com/runtimeverification/llvm-backend/issues/810, the last outstanding bit of migration that needed to happen for us to support LLVM 16+ opaque pointers. The full context for this change is in the original issue.
To fix the issue, we need to delay the conversion from `ValueType` to `llvm::Type *` until a deeper point in the call stack when emitting calls to `addMatchFunction`. The changes here are designed to minimise the surface area of modified code; we can get away without changing the `MatchLog` data structure or the `printValueOfType` function by just converting `ValueType`s to an _imitation_ of the legacy LLVM type strings. We might want to revisit this architecture in the future, but for now I'm happy with the design.
The changes made here are tested by …
> Fix type printing in LLVM >= 16

- test/defn/io.kore
Similarly to https://github.com/runtimeverification/llvm-backend/pull/864, this PR addresses a flaky test that can be left in an intermediate state between runs of the test suite. In this case, we solve the problem by cleaning up all old `io_log.txt` files _before_ the relevant test runs, rather than at the end.
> Fix flaky IO test

- bin/llvm-kompile
- bin/llvm-kompile-clang
- include/kllvm/codegen/ApplyPasses.h
- lib/codegen/ApplyPasses.cpp
- tools/llvm-kompile-codegen/main.cpp
This follows #794 in the pursuit of improving the performance of the backend's compilation pipeline; the philosophy of the change is identical (remove places where we materialize code in the compilation pipeline, and instead use the LLVM libraries to do it all in-memory).
There are a few more changes required in this PR in order to expose the full generality of the options we previously supported for `llc`, but these are largely boilerplate.
The default behaviour of `llvm-kompile` is now to use the new pipeline, but it's possible to opt back out of it for debugging.
> Inline invocations of `llc` for main module

- lib/codegen/ApplyPasses.cpp
- lib/codegen/CMakeLists.txt
- test/lit.cfg.py
This PR is a hotfix for a [broken](https://github.com/runtimeverification/k/pull/3728) backend update job.
When using the new [inlined version of `llvm-kompile`](https://github.com/runtimeverification/llvm-backend/pull/814), we were incorrectly using the result of `sys::getDefaultTargetTriple()` as our target for machine code emission, rather than the consistent value selected by running Clang on an empty input file.
On newer versions of macOS, this produces warnings like:
```
ld: warning: object file (tmp.1YutNb2k5B.o) was built for newer macOS version (14.0) than being linked (10.12)
```
when running `llvm-kompile`. These warnings were silently absorbed by CI as they are just warnings, but they are a) noisy and b) break the K test suite when grepping for error messages in failed …
> Hotfix for K LLVM backend update

- config/macros.h
- lib/codegen/ApplyPasses.cpp
- lib/codegen/CMakeLists.txt
- lib/codegen/CreateTerm.cpp
This PR follows up on #869 to refactor our use of CMake to configure C++ code with build-specific information. Instead of configuring individual files, we push all `@...@` stanzas into `config/macros.h` and use that file as the single source of configured literals.
There is a small change to the implementation of the LLVM header in `CreateTerm.h` to support this.
> Refactor cmake-configured C++ code

- nix/llvm-backend-matching.nix
- nix/overlay.nix
No longer needed as it has been implemented in the K repo as `llvm-kompile-matching` (https://github.com/runtimeverification/k/pull/3659)
> revert Add llvm-backend-matching as an executable #827

- INSTALL.md
- cmake/FindLLVM.cmake
- default.nix
- flake.nix
- include/kllvm/codegen/Util.h
- lib/codegen/ApplyPasses.cpp
- lib/codegen/CreateStaticTerm.cpp
- lib/codegen/CreateTerm.cpp
- lib/codegen/Debug.cpp
- lib/codegen/Decision.cpp
- lib/codegen/DecisionParser.cpp
- lib/codegen/EmitConfigParser.cpp
- lib/codegen/Util.cpp
Having dropped support for Ubuntu Focal in K, we no longer need to support versions of LLVM older than 15; this PR makes the required changes to the backend to drop support for those older versions. I will follow up with a K PR to update the corresponding documentation.
Fixes https://github.com/runtimeverification/llvm-backend/issues/868
> Drop LLVM <15

- .github/workflows/clang-format-check.yml
- include/kllvm/ast/AST.h
- tools/k-rule-apply/auxiliar.h
This PR implements a feature requested by @gtrepta whereby `getSort()` calls on _domain value_ patterns that are part of a definition will return the first formal sort argument (e.g. `SortX{}` in `\dv{SortX{}}("...")` rather than `nullptr`. Doing so simplifies printing and serialization logic in some parts of the backend.
As well as CI passing, I have tested this on upstream K and it does not appear to break anything; my suspicion is that we just weren't relying on these sorts being `nullptr` previously.
The PR also pins a specific version of `clang-format`, which we weren't doing previously.
> Use domain value argument sort if possible

- include/kllvm/codegen/ProofEvent.h
- lib/codegen/CreateTerm.cpp
- lib/codegen/EmitConfigParser.cpp
- lib/codegen/ProofEvent.cpp
As discussed previously, this PR is an initial cleanup and refactoring effort for the existing proof-hint generation code implemented for rewrite, function and hook events. The changes in this PR don't add any new features to the traces; they just reorganise the existing code.
Most of the changes made are documentation and identifying duplicated code across different call-sites that can be merged together.
I plan to port the reorganisation in #862 over to the infrastructure in this PR once it is merged.
The trace format is not tested in the backend currently (this is future work), but I have verified that a proof trace (that uses all event types) generated using this branch is byte-for-byte identical to one generated from the current master branch.
> Refactoring proof trace code

- docs/proof-trace.md
- include/kllvm/codegen/ProofEvent.h
- lib/codegen/CreateTerm.cpp
- lib/codegen/Decision.cpp
- lib/codegen/ProofEvent.cpp
- runtime/take_steps.ll
- runtime/util/ConfigurationPrinter.cpp
- runtime/util/ConfigurationSerializer.cpp
This PR is a reworking of the changes initially made by @gtrepta in #862, to include the cleaned-up proof infrastructure in #876.
The changes here are pretty minimal; we need to split the "rewrite" event into a pre and post part so that the arity / ordinal and resulting configuration can be emitted separately. Other than that, it's just a question of reusing some of the boilerplate in #862 that assembles the substitution information in the event.
~~There is one major issue with the change here, which @gtrepta also identified in his initial version of this change. We can only emit resulting configurations for top-level rewrites (that is, we cannot print the resulting _term_ from calling a function). Doing so breaks TCO for the generated interpreter badly enough that some backend tests …
> Move rewrite event emission

- bin/llvm-kompile
- bin/llvm-krun
- lib/codegen/CreateTerm.cpp
- lib/codegen/ProofEvent.cpp
- test/defn/imp-proof.kore
- test/lit.cfg.py
This PR adds two flags to our scripts to turn the proof hint instrumentation and output on and off:
- a flag `--proof-hint-instrumentation` is added to the `llvm-kompile` script. When the flag is passed the generated llvm code is instrumented with proof hint generation code.
- a flag `--proof-hints` is added to the `llvm-krun` script. When the flag is passed to an instrumented interpreter binary, the binary will output proof hints.
> Flags to turn on/off proof hint instrumenation and output

- include/kllvm/codegen/Debug.h
- include/kllvm/codegen/Options.h
- lib/codegen/ApplyPasses.cpp
- lib/codegen/CMakeLists.txt
- lib/codegen/Debug.cpp
- lib/codegen/Options.cpp
- lib/codegen/ProofEvent.cpp
- tools/llvm-kompile-codegen/main.cpp
When proof hint generation is enabled, we want to be able to emit every intermediate configuration into the trace; the current implementation only does so when we are at a rewrite step that has not used iterative compilation to merge two decision tree matrices. This PR disables the use of iterative compilation and residuals when generating code with trace instrumentation.
Doing so has no effect on the soundness of the generated code; iterative compilation is a rarely-used optimization.
The first 3 commits in this PR are a slight refactoring of our usage of command-line options when running code generation.
> Disable iterative matching when proof hints are enabled

- .github/workflows/test-flake.yml
These tests seem prone to [timing out in the post Cachix step](https://github.com/runtimeverification/llvm-backend/actions/runs/6885333562/job/18729317083?pr=882); this PR attempts to fix the issue by moving the tests off the ephemeral runner and onto regular self-hosted ones.
> Drop ephemeral runner for Flake test

- lib/codegen/ProofEvent.cpp
We were incorrectly emitting proof instrumentation when these event functions were called; this PR adds the same flag check to their preludes as the other events have. I have verified that there is no proof-related generated code in the module produced by the code generator after this change.
> Missing cases for proof instrumentation flag

- bindings/python/ast.cpp
- include/kllvm/parser/KOREParser.h
- test/python/test_parser.py
This is a small PR to expose the KORE sort parser to Python in the same way that we already do for patterns and definitions; as usual for Python binding features it adds a small smoke test, but Pyk should add more comprehensive tests when this change is upstreamed.
Fixes https://github.com/runtimeverification/llvm-backend/issues/901
> Expose sort parser to Python bindings

- .github/workflows/test-flake.yml
The github actions parser doesn't like the internal JQ pipeline being split across two lines; this was silently breaking the manual cachix push.
> Fix shell quoting in cachix push

- include/kllvm/ast/AST.h
- include/kllvm/binary/ProofTraceValidator.h
- include/runtime/header.h
- lib/ast/AST.cpp
- runtime/util/ConfigurationSerializer.cpp
- runtime/util/util.cpp
This is an alternative formulation to https://github.com/runtimeverification/k/pull/3829; that PR contains the original context for why this change is necessary. Rather than adding a regular symbol to the K standard library source and using a check in the frontend to ensure that user code doesn't mention it, we directly emit a symbol into each definition with a name that the frontend cannot reference.
We also bump the version number for the proof hint format so that this non-standard symbol must be explicitly accepted by the Python client code.
> Add raw term symbol to definitions

- bin/llvm-kompile-clang
- bindings/CMakeLists.txt
- bindings/c/CMakeLists.txt
- bindings/c/lib.cpp
- bindings/core/CMakeLists.txt
- bindings/core/include/bindings/core/core.h
- bindings/core/src/core.cpp
- bindings/python/CMakeLists.txt
- bindings/python/runtime.cpp
- include/kllvm/bindings/core/core.h
- runtime/util/ConfigurationPrinter.cpp
- runtime/util/ConfigurationSerializer.cpp
- test/python/Inputs/simplify.kore
- test/python/k-files/simplify.k
- test/python/simplify.py
This PR exposes the concrete term simplification routines already used by the booster to the Python bindings so that they can be called from Pyk. Specifically, it adds two free functions to the `runtime` module:
```python
simplify_pattern(Pattern, Sort) -> Pattern
simplify_bool_pattern(Pattern) -> bool
```
These are exposed as free functions because they depend on the runtime library and so can't be automatically bound to the `Pattern` class as methods; I suggest Pyk probably wants to monkey-patch them into its `Pattern` class along with some kind of dynamic check for whether the `runtime` module has been loaded or not.
Previously, the C and Python bindings didn't share a great deal of code; the simplification routine is the first bit of non-trivial behaviour that they need to share. I …
> Add term simplification to Python bindings

- bindings/c/lib.cpp
- include/kllvm/ast/AST.h
- lib/ast/AST.cpp
- lib/codegen/CreateTerm.cpp
- lib/codegen/Decision.cpp
- lib/codegen/EmitConfigParser.cpp
- lib/codegen/ProofEvent.cpp
- runtime/util/ConfigurationParser.cpp
- tools/llvm-kompile-codegen/main.cpp
A common pattern in the backend's code is to do the following:
```c++
std::ostringstream out;
pattern->print(out);
do_something(out.str());
```
In #911, we introduced a helper function `ast_to_string` that wraps this common pattern up; this PR follows up that change by mechanically refactoring the remainder of the codebase to use the helper. After the change, the above code would be:
```c++
do_something(ast_to_string(*pattern));
```
Each commit in the PR (bar the first) applies the same conceptual refactoring to a single file; no actual behavioural changes other than in the first commit are implemented, and so this should be an easy PR to review.
In future work, I'd like to further clean up this code and make better use of `fmt` across the codebase, but for now this is a useful …
> Refactor usages of `std::ostringstream`

- bin/llvm-kompile-clang
- debug/kgdb.py
- include/runtime/header.h
- lib/codegen/EmitConfigParser.cpp
- runtime/collections/lists.cpp
- runtime/collections/maps.cpp
- runtime/collections/rangemaps.cpp
- runtime/collections/sets.cpp
- runtime/util/ConfigurationSerializer.cpp
- runtime/util/util.cpp
- test/defn/k-files/wasm-maps.k
- test/defn/wasm-maps.kore
- test/input/wasm-maps.in
- test/output/wasm-maps.out.diff
- unittests/runtime-collections/lists.cpp
- unittests/runtime-ffi/ffi.cpp
- unittests/runtime-io/io.cpp
- unittests/runtime-strings/bytestest.cpp
This PR changes the way that we print and serialize collection elements. Previously, we assumed that the elements of collections were uniformly of sort `KItem`. This is indeed the case for the built-in `Map`, `Set` and `List` sorts, but the assumption breaks down in the presence of custom collection sorts that sort their elements differently (for example, defining a custom `Map` that requires its keys to only be integers). Terms of these custom sorts are printed incorrectly, with spurious injections into `KItem` rather than their actual element sorts.
The solution to the problem is to look up the argument sorts of the element constructor when printing and serializing collections; the required information is already present in the binary and just requires a bit of refactoring to access. …
> Print hooked sort elements correctly

- .clang-tidy
- bindings/python/ast.cpp
- lib/codegen/DecisionParser.cpp
This PR enables the "miscellaneous" set of `clang-tidy` checks. Adopting these checks requires basically no changes to our code, but I've left the following checks disabled:
- Disallowing recursion
- Disallowing unused parameters with names (e.g. this check prefers `T f(A, B)` to `T f(A a, B b)` when `a` and `b` are unused).
- Using public data members in classes; we do this in a few places and I think it's an acceptable decision.
As ever, happy to bikeshed but this shouldn't be a controversial one at all.
> Enable clang-tidy miscellaneous checks

- lib/ast/AST.cpp
The frontend test suite catches a bug introduced in #933, where byte literal values that overflow a signed character are printed incorrectly. I took a look at the best place to test this (i.e. whether it was worth backporting the relevant test into the backend test suite), and it is indeed in the frontend because of the way that we provide test cases in each project.
I have run the downstream K test suite and verified that it passes with this fix applied.
Fixes: https://github.com/runtimeverification/k/pull/3883
> Hotfix for byte escaping issues

- bindings/python/runtime.cpp
- test/python/test_steps.py
This PR fixes a long-standing issue in the backend's binding code, which is that the call to `initStaticObjects()` when the Python module is _bound_ does not affect the process that actually runs the backend interpreter. A consequence of this is that GMP is never told to use our GC'ed memory allocators, and so any code using integer operations ends up leaking lots of memory when it runs for a long time.
To fix Python code that uses the bindings:
* Call `init_static_objects` on application startup
* If an application _only_ does function evaluation or simplification, you may also want to call `free_all_gc_memory` occasionally as the backend will not do so autonomously unless a rewrite step is taken.
Relevant:
* #770
* #922 (has reproduction instructions)
> Enable fixes for memory leaks in bindings

- bin/utils.sh
- nix/llvm-backend.nix
In https://github.com/runtimeverification/llvm-backend/pull/833 we changed from the built-in date command to perl for getting the system time in ms; this caused some weird interactions with the OS when installed via `kup`: https://github.com/runtimeverification/kup/issues/80
This PR drops our use of `perl` and instead uses an equivalent `python3` command, which we already depend on when building the backend.
> Use python rather than perl for profiling

- bindings/python/ast.cpp
- include/kllvm/binary/ProofTraceParser.h
- lib/binary/CMakeLists.txt
- lib/binary/ProofTraceParser.cpp
- test/python/Inputs/proof-trace.in
- test/python/Inputs/proof-trace.kore
- test/python/k-files/proof-trace.k
- test/python/test_proof_trace.py
- tools/kore-proof-trace-test/main.cpp
- tools/kore-proof-trace/main.cpp
This PR adds python bindings for the proof trace parser.
The PR also contains two more changes, that became apparent while I was working on the bindings:
- The `LLVMRewriteTrace` object becomes a `class` rather than a `struct` and we provide bindings for that class.
- The `ProofTraceParser` object does not accept the expected hints version as an argument to its constructor, but rather stores this information in a static constant. This made more sense since the parser currently supports only the latest hints version. In the future, if we want the parser to support older versions we can revisit this.
> Python bindings for the proof trace API

- lib/parser/KOREScanner.l
Fixes #948
Flex does not directly support Unicode, but it does support `%option 8bit` where every 8-bit byte in the input stream is treated as a separate character. To fix #948, rather than escaping in the frontend then, we can just accept any byte sequence inside comments (in practice always UTF-8), allowing the original source text to be passed through unmodified.
However, 8-bit mode also makes it so that `.` and negated character classes `[^bar]` accept non-ASCII bytes, which we sometime want to disallow, e.g., in string literals, so we need to update every such regex accordingly.
> Set `%option 8bit` in `KOREScanner.l`

- .clang-tidy
- bindings/python/ast.cpp
- lib/ast/AST.cpp
- lib/codegen/EmitConfigParser.cpp
- runtime/collections/kelemle.cpp
- runtime/io/io.cpp
- runtime/meta/ffi.cpp
- runtime/strings/strings.cpp
- tools/k-rule-apply/main.cpp
- tools/kore-expand-macros/main.cpp
This is another PR in my ongoing series to enable more clang-tidy checks for the codebase. As previously, each commit in this PR fixes the issues flagged by a single check, and can / should be reviewed independently.
> Enable clang-tidy bugprone checks

- include/kllvm/ast/AST.h
- lib/ast/CMakeLists.txt
- lib/ast/definition.cpp
The method implemented here collects all the sorts that are hooked to a particular implementation; typically this will be a singleton set, but it is possible in theory to have user code add additional sorts.
Motivated by @Scott-Guest's observation on #950 that it is not safe to assume `SortBytes` is the only sort on which byte hooks can be called; we instead need to compute the set of sorts greater than any sort hooked to `BYTES.Bytes` (using code in #951).
> Implement helper to collect sorts hooked to a particular implementation

- test/defn/io.kore
- test/defn/test26.kore
These tests were prone to leaving files hanging around on disk after they were run; nothing _breaks_ if this happens but it's a minor irritant having it all build up.
> Make a couple of tests cleaner

- bindings/c/lib.cpp
While working on these bindings, I noticed that we were not taking best advantage of C++ and were writing some quite C-like code in places. This PR cleans up the following things:
- Use aggregate constructors to build internal types, rather than assigning to members
- Use `unique_ptr`s to manage allocated intermediate objects
- Use a helper function to manage C strings
> Minor cleanups to C bindings

- nix/llvm-backend.nix
- nix/overlay.nix
In order to support seamless integration between the llvm backend and pyk on nix, we need to build the llvm backend with the same version of python that we use at runtime. The version we use at runtime, according to pyk's `pyproject.toml` file, is 3.10, so we update the version of python we use in the nix derivation for the llvm backend.
> update to python 3.10

- nix/overlay.nix
This PR cuts out a bunch of Nix code that we seemed to be using only for historical purposes related to old Nixpkgs bugs and older LLVM versions.
> Simplify nix overlay code

- include/kllvm/ast/AST.h
- include/kllvm/binary/ProofTraceParser.h
- include/kllvm/binary/deserializer.h
- include/kllvm/binary/serializer.h
- lib/binary/serializer.cpp
- runtime/util/ConfigurationSerializer.cpp
We would rather have a string here than a vector as it will allow for more efficient expansion and bulk copying when required (`std::vector` has to default-initialize when reserving capacity, while a string doesn't).
> Switch out serializer backing storage vector for a `std::string`

- include/runtime/header.h
- lib/codegen/EmitConfigParser.cpp
- runtime/util/ConfigurationSerializer.cpp
When a symbol has no formal sort parameters, we can directly look up its name in the interpreter's data tables and use a faster path for serialization (instead of parsing every symbol and doing a lookup in a hash table to get the sort arguments and name).
Fixes https://github.com/runtimeverification/llvm-backend/issues/974
> Precompute serialized symbols 

- flake.lock
- flake.nix
As discussed; the version pinned here is actually the version already being used by the backend.
> Follow rv-tools Nixpkgs version

- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
When pyk generates new KORE modules for use internal to its prover, it creates rules whose structure is different from any rule which is generated by the K frontend. As a result, splitTop does not know how to handle such axioms. We thus need to extend splitTop to support this type of rule in order to support parsing these modules as needed by the Maude backend.
> support pyk form of axioms in splitTop

- bindings/python/ast.cpp
- include/kllvm/ast/AST.h
- include/kllvm/ast/attribute_set.h
- include/kllvm/codegen/Debug.h
- lib/ast/AST.cpp
- lib/ast/CMakeLists.txt
- lib/ast/attribute_set.cpp
- lib/ast/definition.cpp
- lib/codegen/CreateStaticTerm.cpp
- lib/codegen/CreateTerm.cpp
- lib/codegen/Debug.cpp
- lib/codegen/Decision.cpp
- lib/codegen/EmitConfigParser.cpp
- lib/parser/KOREParser.cpp
- lib/printer/printer.cpp
- tools/k-rule-apply/main.cpp
- tools/k-rule-find/main.cpp
- tools/kore-expand-macros/main.cpp
- tools/llvm-kompile-codegen/main.cpp
This PR implements a more limited version of the type-safe attribute infrastructure that we use in the K frontend; by doing so we can construct a canonical list of the attributes that we _actually_ use in the backend, and avoid working with string data when we don't need to be.
The core of the change is a new `attribute_set` structure that _accepts_ attributes permissively from the parser, but only allows key-value lookup via a limited set of whitelisted attribute keys. There are a couple of places in the code that need to access the full set of attributes, ignoring the whitelist:
* When pretty-printing via iteration over the set of stored attributes
* When returning the set of attributes to Pyk via the Python bindings
Both of these code paths have comments to make sure they are used …
> Implement type-safe attributes

- lib/ast/AST.cpp
- lib/codegen/CreateTerm.cpp
For https://github.com/runtimeverification/k/issues/3976
There's a special case for a hook namespace in `ARRAY` which falls back to K semantics for those symbols. The frontend wont emit any hook attributes in that namespace for the ARRAY module anyway so it can safely be removed.
> Remove array namespace check

- test/defn/k-files/lambda-anywhere.k
- test/defn/k-files/lambda.md
- test/defn/k-files/test21.md
- test/defn/k-files/wasm-maps.k
Part of runtimeverification/k#4009
Replace usages of deprecated tokens:
- `syntax priorities` with `syntax priority`
- `require` with `requires`
- `import` with `imports`
> Replace usages of `priorities`, `require`, and `import`

- include/runtime/arena.h
- runtime/alloc/alloc.cpp
- runtime/alloc/arena.cpp
- runtime/collect/collect.cpp
This fixes a rather unpleasant bug when using the C bindings from the Haskell backend, whereby [recent changes](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246462) to the dynamic loader on macOS break symbol lookup from dynamic libraries.
The result of this change is that calls to the backend's `arenaAlloc` function were ending up in the Haskell RTS's function of the same name, meaning that we got garbage memory allocated all over the place. There's no sensible fix here other than to rename our function and avoid the collision by doing so.
> Rename `arenaAlloc` to fix collision with GHC RTS

- INSTALL.md
- cmake/FindDependencies.cmake
When setting CLion up to do some automatic refactoring, it complained about not being able to find this dependency. Some digging reveals it was added in the very first commit of the backend's build system and has not been touched since, so I think it's safe to remove.
> Remove `zlib` dependency

- matching/src/main/java/org/kframework/backend/llvm/matching/Location.java
- matching/src/main/java/org/kframework/backend/llvm/matching/MatchingException.java
- matching/src/main/java/org/kframework/backend/llvm/matching/Source.java
- matching/src/main/scala/org/kframework/backend/llvm/matching/Matrix.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/Parser.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/SortCategory.scala
Part of: https://github.com/runtimeverification/llvm-backend/issues/999
We are currently working on removing the reverse dependency that the LLVM backend has on the K frontend's data structures; this PR takes a step towards that goal by removing the backend's use of the K Source and Location classes. These classes are only ever used in the matching compiler as simple PODs that carry around data, so they can be replaced trivially with Java classes here.
This PR needs a matching change to the K frontend to work, along with appropriate lockstep merging.
Also contains a minor fix in https://github.com/runtimeverification/llvm-backend/pull/1002/commits/4b644b04278cf030580276288785307167276903 for an edge case in the exhaustiveness checker for rules with no location; we want to propagate an …
> Remove usages of K source and location classes

- matching/pom.xml
- nix/llvm-backend-matching.nix
- nix/overlay.nix
https://github.com/runtimeverification/llvm-backend/pull/1006 is failing because the Scala Maven plugin is trying to download the sources for the compiler bridge, but can't do so outside of a Nix FOD. This PR adds the bridge to the manually-downloaded Maven artifacts (as we did in https://github.com/runtimeverification/k/pull/4055)
> Add source artifacts for Scala compiler bridge

- bindings/python/ast.cpp
This is a requirement from the Math Proof Generation Team of $Piˆ2$ to get easy access to the Pattern of a requires clause.
This PR must be merged before this [PyK PR](https://github.com/runtimeverification/pyk/pull/1056) that will properly expose this binding to the Pi2 project.
> Adding `get_requires()` to Python bindings

- runtime/collect/collect.cpp
This PR fixes a bug in GC discovered while testing KEVM with the Ethereum test suite.
Specifically we want to make sure that the affected operations invoke move constructors rather than copy constructors.
> Small bug fix for GC

- bindings/python/ast.cpp
- docs/proof-trace.md
- include/kllvm/binary/ProofTraceParser.h
- include/kllvm/codegen/ProofEvent.h
- include/runtime/header.h
- lib/binary/ProofTraceParser.cpp
- lib/codegen/ProofEvent.cpp
- runtime/util/ConfigurationSerializer.cpp
- runtime/util/util.cpp
- test/output/imp-proof/imp-proof.expanded.out.diff
- test/output/imp-proof/imp-proof.out.diff
- test/output/imp-slow-proof/imp-slow-proof.expanded.out.diff
- test/output/imp-slow-proof/imp-slow-proof.out.diff
This modification was proposed by the LLVM Backend and Math Proof Generation Teams from Pi2 to optimize the Hints generated by the `llvm-krun` as constructing and parsing the boolean values of the side conditions takes some time. Then, we choose to simplify the way we're generating these hints.
> Modify `side_condition` results to be only `false` or `true` in Proof Hints

- include/kllvm/codegen/CreateTerm.h
- lib/codegen/CreateTerm.cpp
- test/output/imp-proof/imp-proof.expanded.out.diff
- test/output/imp-proof/imp-proof.out.diff
- test/output/imp-slow-proof/imp-slow-proof.expanded.out.diff
- test/output/imp-slow-proof/imp-slow-proof.out.diff
This PR fixes 2 issues with the generation of locations for the hook and function proof hint events.
- The starting location stack is now the empty stack as opposed to the `"0"` stack. This is because the math team assumes that the first location in the stack corresponds to an argument of the top cell in the configuration and not the top cell constructor.
- The previous method for skipping locations that correspond to injections, namely skipping a location when the child of a term is an injection, was leading to errors when it combined with the injection compaction optimization. Specifically, the method could lead to skipping an extra location in the case where the algorithm needed to generate code for possibly applying an injection compaction. We change the algorithm for skipping …
> Fix locations in proof hints

- test/defn/k-files/wasm.k
Part of runtimeverification/k/issues/4295
Escapes all usages of `-` and `^` within character classes to align with the new regex syntax.
> Update regex terminals to match new syntax

- bin/llvm-kompile-testing
Fixes #858.
This `--` was previously removed [here](https://github.com/runtimeverification/llvm-backend/pull/719) by @Baltoli. We need to double-check if this won't break anything.
> Adding `--` back to `llvm-kompile` call in `llvm-kompile-testing`

- include/kllvm/ast/attribute_set.h
We have seen that the `definition.kore` has been produced in a different order depending on the OS, which creates a flaky error for some tools like `llvm-komplie-compute-ordinal` and `llvm-kompile-compute-loc`, an error on #1053 MacOS tests, and some frontend errors as well. 
This PR aims to fix that issue by replacing the data structure used to store the attributes.
> Using `map` instead of `unordered_map` to ensure reproducibility of kore definition generation

- bin/llvm-krun
An unnecessary `set -x` got upstream and is messing up with the CI test's visualization. This PR deletes it.
> Update llvm-krun: removing `set -x`

- bin/llvm-kompile
- bin/llvm-kompile-clang
- include/kllvm/codegen/ApplyPasses.h
- include/kllvm/codegen/SetVisibilityHidden.h
- lib/CMakeLists.txt
- lib/codegen/ApplyPasses.cpp
- lib/set-visibility-hidden/CMakeLists.txt
- lib/set-visibility-hidden/SetVisibilityHidden.cpp
- tools/llvm-kompile-codegen/CMakeLists.txt
- tools/llvm-kompile-codegen/main.cpp
This flag is used to assist with the process of building an application that links against more than one llvm backend semantics.
It can be used in roughly the following way:
1. Compile the llvm backend with the `clang++` flag `-fvisibility=hidden`.
2. Run `llvm-kompile definition.kore dt library --hidden-visibility -- -shared entry.cpp -o definition.so` in the kompiled directory.
3. Link `definition.so` into your application. It will have all the symbols of `entry.cpp` and `entry.cpp` will be able to access any symbol in the semantics, but those internal symbols will not be visible to the application.
The application can do this with multiple semantics and there will be no linker issue. I have tested some basic examples that show that each semantics can separately apply its own rewrite …
> --hidden-visibility flag to llvm-kompile

- .github/workflows/test.yml
Part of: https://github.com/runtimeverification/k/issues/4368
We no longer want to support these machines, and so we should remove them from all the CI matrices that we're using across the organisation.
> Drop intel macOS support in CI

- bin/llvm-kompile-testing
- nix/overlay.nix
Previously, the testing script would invoke Maven every time it compiled a pattern-matching tree; this was slow and made the CI process prone to intermittent network failures. This PR addresses the issue by instead directly invoking the compiled JAR file that we already built with Maven.
Fixes https://github.com/runtimeverification/llvm-backend/issues/1055
> Don't invoke Maven every time we run a test

- flake.lock
- nix/llvm-backend.nix
- nix/overlay.nix
This will allow us to run LLVM 18 in CI; the only change needed to our Nix code here is a small difference in the API of the `llvmPackages_*` derivations.
> Update to new Nixpkgs version

- include/kllvm/binary/ProofTraceParser.h
- lib/binary/ProofTraceParser.cpp
- test/lit.cfg.py
- tools/kore-proof-trace/main.cpp
This is a pretty straightforward diff. We can reuse the code for parsing events and the proof trace header, so we just need to create an entry point to the streaming parser that invokes the relevant parsing logic and returns events one at a time, and then write code to test it. We test it by modifying lit tests that test the proof hints so that they test both parsers. This means we get the advantage of the entire coverage set of tests that we imported from the math proof repo.
> Write streaming event parser for proof hints

- flake.nix
We have already made all the changes required to update the backend to LLVM 18:
- https://github.com/runtimeverification/llvm-backend/pull/1068
- https://github.com/runtimeverification/llvm-backend/pull/1070
This PR finalises the process by adding LLVM 18 to our CI matrix.
> Update CI matrix for LLVM 18

- tools/kore-rich-header/main.cpp
Closes https://github.com/Pi-Squared-Inc/pi2/issues/1483
This simple PR addresses @Baltoli's suggestion to include `cl::opt` in the `kore-rich-header` to improve the user experience for a broader audience. I also added `-o/--output` support to improve the tool's usability and compatibility with other tools and scripts.
> Adding `llvm:cl::opt` support to `kore-rich-header`

- package/debian/rules.jammy
- package/debian/rules.noble
This PR explicitly disables LTO via the backend's own option when building Debian packages, rather than relying on the Debian Makefile infrastructure to propagate the appropriate flags down through CMake. We already do the same thing when building via Nix.
The issue here manifests strangely (https://github.com/runtimeverification/llvm-backend/issues/1038). In this case, what's happening is that LTO being enabled causes the runtime's static libraries to get built as archives of `.bc` files rather than actual objects. These bitcode files then contain inline assembly directives based on the C++ code's directives, which contain absolute paths referencing the _build system_ rather than the _runtime system_. We therefore need to disable LTO so that the assembly directives are resolved fully …
> Disable LTO when building Debian packages

- .github/workflows/release.yml
In #1072, we changed the names of some workflow steps. This introduced a typo in the release workflow that's been preventing us from cutting releases; this PR is a straightforward fix for that typo.
> Fix typo in release workflow

- include/kllvm/codegen/CreateTerm.h
- include/runtime/header.h
- lib/codegen/CreateTerm.cpp
- runtime/alloc/alloc.cpp
- runtime/alloc/arena.cpp
- runtime/util/ConfigurationParser.cpp
- unittests/runtime-collections/lists.cpp
This is one of a sequence of PRs designed to make progress towards generating stack maps so that we can trigger the GC during allocation rather than in between rewrite steps only. The first few PRs will be preliminaries that add small features that will be used by future PRs.
This PR adds a global variable that controls whether or not garbage collection is enabled. This boolean flag is disabled during certain call frames that it would be difficult to walk the stack of. In particular, we disable the flag during:
* allocations that occur inside immer
* calls to hooks
* allocations that occur inside GMP and MPFR
* construction of the initial configuration
The boolean flag is currently unused. It will be used in a future pull request to determine whether the allocator is allowed to trigger …
> add flag to control whether gc should be enabled or not

- bindings/python/ast.cpp
- test/python/test_proof_trace.py
This small PR only updates the `LLVMEventType` name to `EventType` to preserve the `LLVM` prefix to be used by the wrapper classes created on PyK that export these bindings. 
This PR also exposes the `__repr__` function of `llvm_rewrite_trace_iterator`. The print function was already implemented but has yet to be exposed; we decided to expose it as the binding as it can be helpful for debugging.
> Update name of `EventType` and expose `__repr__` from `llvm_rewrite_trace_iterator`

- include/kllvm/codegen/Util.h
- include/runtime/alloc.h
- lib/codegen/Decision.cpp
- lib/codegen/Util.cpp
- runtime/alloc/alloc.cpp
- runtime/collect/collect.cpp
This is one of a sequence of PRs designed to make progress towards generating stack maps so that we can trigger the GC during allocation rather than in between rewrite steps only. The first few PRs will be preliminaries that add small features that will be used by future PRs.
This PR separates koreCollect's logic for collecting the gc'd heap from its logic for resetting the alwaysgcspace arena. We separate the logic for resetting the alwaysgcspace arena into a new method, `kore_clear`. This function is no longer called by the garbage collector, but it is called after every rewrite step. This is a slight increase in overhead since we are clearing it more frequently, but the flip side is that it should have better locality which may improve the processor's dcache, since we are clearing it …
> add kore_clear function that clears alwaysgcspace on every step

- .github/workflows/clang-format-check.yml
- .github/workflows/test.yml
These jobs were previously running on an old version of Ubuntu, the image for which will be deprecated at some point. This PR just bumps them to use a newer version; the jobs aren't interacting with the OS in any meaningful way so this won't be a breaking change.
> Move simple CI jobs to latest Ubuntu version

- include/kllvm/ast/util.h
- lib/ast/util.cpp
- test/defn/compute-ordinal-loc/definition.kore
- test/defn/compute-ordinal-loc/source_line_number_rule
- tools/llvm-kompile-compute-loc/main.cpp
- tools/llvm-kompile-compute-ordinal/main.cpp
These binaries were not quite feature-complete with their original intended purpose, probably primarily because at the time at which they were reimplemented, the past version of them was somewhat broken.
This PR adds the following features:
1. Outputting the k location is the default in llvm-kompile-compute-loc
2. If a k location does not exist, it falls back to the kore location rather than crashing.
3. The output is formatted with both a filename and a line number.
4. In llvm-kompile-compute-ordinal, you can specify a filename and it will search for the ordinal of a k rule on that line of that file in the input definition.
> update llvm-kompile-compute-loc and llvm-kompile-compute-ordinal

- bin/llvm-kompile
- include/kllvm/codegen/Decision.h
- lib/codegen/Decision.cpp
- runtime/util/CMakeLists.txt
- runtime/util/clock.cpp
- scripts/matching-profile/join-with-locations
- scripts/matching-profile/matching-profile-formatter
- scripts/matching-profile/sum-matching-profile
- tools/llvm-kompile-codegen/main.cpp
We add a new flag to `llvm-kompile` which, when enabled, instruments the `k_step` function and the optimized `step_<ordinal>` functions with calls to a new translation unit, clock.cpp, which contains some very basic use of `clock_gettime` in order to determine how much time is being spent doing pattern matching in order to try to apply each rewrite step. The resulting file contains data about the ordinal of the rule that applied and the time it took to determine that that rule should apply. It emits this data on stderr in a tabular format that can be read easily by a computer. This information is useful in determining how to optimize pattern matching in cases where it is still not clear where time is being spent even after `kompile -O3 --iterated-threshold 1` is passed. When the flag is …
> llvm-kompile --profile-matching

- .github/workflows/ci-tests.sh
- include/kllvm/codegen/Options.h
- include/kllvm/codegen/SetVisibilityHidden.h
- lib/codegen/ApplyPasses.cpp
- lib/codegen/CreateTerm.cpp
- lib/codegen/Decision.cpp
- lib/codegen/Options.cpp
When we migrated the llvm backend optimization pipeline from being applied by `opt` to being applied by `llvm-kompile-codegen`, we made an error. The code generator was not, in fact, applying the `opt` transformation pipeline correctly. This means that `kompile -O2` will not, in fact, apply `llc -O2` to the bitcode generated by the llvm backend, leading to a significant performance regression.
While this PR does not entirely fix the issue (an upstream change to the K frontend is also required), it fixes the issue within this repository. We see a roughly 1.5x speedup in runtime when `-O2` is passed to kompile. We do lose something in compilation time, however. This is normal; compiling with optimizations is more expensive, we just weren't doing it correctly before.
The main changes in this …
> fix llvm-kompile-codegen so it optimizes code properly

- bindings/c/include/kllvm-c/kllvm-c.h
- bindings/c/lib.cpp
- bindings/core/CMakeLists.txt
- bindings/core/src/core.cpp
- include/kllvm/ast/AST.h
- include/kllvm/bindings/core/core.h
- tools/k-rule-apply/CMakeLists.txt
- tools/k-rule-apply/main.cpp
- tools/k-rule-apply/shims.cpp
- tools/k-rule-apply/shims.h
This PR is a preparatory refactoring that will enable me to fix a problematic bug in the Kasmer project; I've factored out the changes here because they include other related cleanups not directly relevant to the bug I'm fixing in the subsequent PR.
Currently, the `k-rule-apply` tool is explicitly linked against the KORE AST library in order for it to be able to parse a KORE definition and search for an axiom with a particular label. This works fine, but on changing the way that the LLVM backend is linked on macOS, this AST linkage caused a subtle bug to manifest because of the way that `k-rule-apply` uses `dlopen` to inspect a shared library compiled by the backend.[^1]
The fix here is to remove the explicit dependency of this tool on the AST + Parser libraries, and instead push all the …
> Refactor `k-rule-apply` tool

- bin/llvm-kompile-clang
- lib/codegen/ApplyPasses.cpp
- nix/llvm-backend.nix
- test/c/Inputs/flat-namespace.c
- test/c/flat-namespace.kore
- test/c/k-files/flat-namespace.k
This PR fixes two subtle, related issues that are blocking updates from going through downstream in the Kasmer project. At a high level, the issues are:
- Flat namespace linking on macOS produces incorrect symbol lookups in dynamic libraries.
- https://github.com/runtimeverification/llvm-backend/pull/1097 misses a subtle edge case related to tail-call optimisation.
The actual code changes required are small, but warrant some detailed explanation.
For a long time, macOS has implemented a system known as _two-level_ namespaces, whereby undefined symbol names in a dynamic library are prefixed with the name of the library in which the loader expects to be able to find them at run-time. This is a conservative behaviour; even if a symbol with the same name exists in a different library, it …
> Drop flat namespace option

- .github/workflows/release.yml
- .github/workflows/test.yml
This PR removes usages of github secrets in the testing workflow run on CI; this means that external contributors should be able to open PRs from forked repos properly. Making the change here required one step more than the K repo needed (moving a cachix push from testing to release), but I'm pretty confident everything is wired up correctly.
> Accept public PRs for CI

- INSTALL.md
libunwind is not available from Brew, and we don't need it anyway because MacOS LLVM doesn't need it.
> INSTALL: Remove libunwind from MacOS dependencies

- bindings/c/lib.cpp
Using `-1` as the sentinel "not present" value for these weak symbols of type `char` is not correct, as the standard makes no guarantee whether `char` is signed or not; it is therefore possible for an implementation to supply us with a type such that comparing the sentinels with `-1` later is tautologically false.
> Fix tautological comparison error

- .github/workflows/test.yml
- flake.nix
- nix/overlay.nix
This PR adapts the existing integration testing derivation into a development shell that can be used to run individual `lit` test cases more selectively than the broad-strokes `nix flake check` command allows for.
To get a shell with a particular version of LLVM, run:
```console
$ nix develop .#integration-test-shell-18
(nix:nix-shell-env) $
```
Then, you can run `lit` commands as usual.
Fixes #865
> Add interactive testing shell for Nix builds

- package/debian/changelog
- package/debian/control.jammy
- package/debian/control.noble
- package/debian/copyright
This PR removes any final references to my contact details from the LLVM backend repo, and assigns them to @gtrepta instead.
> Remove references to my contact details from repo

- debug/kgdb.py
- debug/klldb.py
GDB/LLDB has been broken for a while, and I suspect it has been broken since PR #1000. 
When `k start` was typed in GDB, we had the following error when pretty-printing the subject:
```Bash
Temporary breakpoint 1, 0x00005555555c00f0 in main ()
0x00005555555bb080 in k_step (subject=Traceback (most recent call last):
File "<string>", line 392, in to_string
File "<string>", line 599, in append
File "<string>", line 381, in isSymbolABinder
AttributeError: 'NoneType' object has no attribute 'value'
Python Exception <class 'AttributeError'>: 'NoneType' object has no attribute 'value'
) at /home/robertorosmaninho/pi2-inc/tests/add-rewrite.k:20
20        rule [state-succ] : s(M:Nat) ~> state(N:Nat, _:Nat) => state(N, s(M))
(gdb)
```
This happens due to the renaming of `table_getSymbolNameForTag` …
> Fixing debugger scripts

- include/kllvm/codegen/CreateTerm.h
- include/kllvm/codegen/Util.h
- lib/codegen/CreateTerm.cpp
- lib/codegen/Util.cpp
Previously, when we were allocating a large term, we would issue a number of repeated calls to kore_alloc. This is inefficient because it has to check whether there is enough space and execute a branch instruction on each allocation. It is more efficient if we do one, larger call to kore_alloc for all the memory that we need.
In order to efficiently implement this, we modify the way we generate calls to kore_alloc in the code generator so that it will place the allocation function at the beginning of the basic block and then, if further allocations are required in the same basic block, it will modify the call to the allocation function so it requests a larger amount of memory. This only happens up to a certain bound, in order to prevent memory from being wasted due to requesting …
> merge allocations in same basic block up to a size bound

- include/kllvm/binary/deserializer.h
- include/kllvm/binary/ringbuffer.h
- include/kllvm/binary/serializer.h
- lib/binary/ringbuffer.cpp
- lib/binary/serializer.cpp
- tools/kore-proof-trace/main.cpp
- unittests/compiler/ringbuffer.cpp
This PR adds implementation for buffered reads/writes from and to the shared memory ringbuffer during hint generation. The previous implementation would synchronize reads and writes at the granularity of one byte which is not ideal for performance. In this PR, we add support for synchronization across reads and writes of larger sizes. Both the ringbuffer-based proof trace reader and writer classes are updated to buffer incoming reads and writes: They collect data into an internal buffer and only interacting with the shared memory ringbuffer when that buffer is full in case of the writer or empty in case of the reader.
> Buffered reads/writes for hint generation with shared memory

- test/lit.cfg.py
This PR disables the shared memory proof trace tests on macOS until we resolve a flaky issue with lingering shared memory objects.
> Disabling shared memory proof trace tests on macos

- include/runtime/proof_trace_writer.h
This PR adds a new subclass of `proof_trace_writer` that is intended to use callbacks into Python code to synchronously communicate proof trace events, instead of serializing them to a file. For now the implementation contains placeholder calls into empty functions. A future PR will replace those placeholders with actual callbacks into Python code.
> Callback-based subclass for the proof trace writer

- cmake/RuntimeConfig.cmake
- config/llvm_header.inc
- include/runtime/arena.h
- lib/codegen/Decision.cpp
- runtime/alloc/arena.cpp
- runtime/collect/collect.cpp
- runtime/lto/alloc.cpp
- unittests/runtime-collections/lists.cpp
- unittests/runtime-ffi/ffi.cpp
- unittests/runtime-io/io.cpp
- unittests/runtime-strings/stringtest.cpp
Previously we were computing whether garbage collection should occur on the hot path, which is not terribly efficient. We now compute this information in a more efficient way and only during slow allocations, leaving the fast path to only load a boolean global variable.
I did some profiling and this doesn't seem to have much impact on total memory usage, nor does it cause significantly more time spent in garbage collection.
> optimize how we check whether gc should happen

- bindings/python/ast.cpp
We missed this feature while implementing the new step event; we now need to add it so the Pi2 MPG Team can handle it on the Python side. A subsequent K PR will also be necessary to correctly expose this feature.
> Exposing `llvm_pattern_matching_failure_event` to Python Bindings

- debug/kgdb.py
- include/runtime/collect.h
- lib/codegen/Decision.cpp
- runtime/alloc/arena.cpp
- runtime/collect/collect.cpp
- runtime/util/ConfigurationParser.cpp
1. Fix a bug causing gdb to crash when pretty printing certain values.
2. Modify llvm backend code to actually respect the value of the `gc_enabled` flag.
> A few minor bug fixes related to Geth Integration

- runtime/util/finish_rewriting.cpp
- test/output/exit-cell/exec0.output-cell.proof.out.diff
Previously, the get_exit_code call would emit events into the proof trace. This is not actually part of the proof of execution though, so we should omit these events.
> disable proof hint generation during call to get_exit_code

- include/kllvm/codegen/ProofEvent.h
- include/runtime/header.h
- include/runtime/proof_trace_writer.h
- lib/ast/definition.cpp
- lib/binary/serializer.cpp
- lib/codegen/ProofEvent.cpp
- runtime/util/ConfigurationSerializer.cpp
- test/input/mint-arith/add160.in
- test/input/mint-arith/add256.in
- test/input/mint-arith/add32.in
- test/input/mint-arith/add64.in
- test/input/mint-arith/add8.in
- test/lit.cfg.py
- test/output/mint-arith/add160.proof.out.diff
- test/output/mint-arith/add256.proof.out.diff
- test/output/mint-arith/add32.proof.out.diff
- test/output/mint-arith/add64.proof.out.diff
- test/output/mint-arith/add8.proof.out.diff
- test/proof/k-files/mint-arith.k
- test/proof/mint-arith.kore
This PR fixes two issues related with the serialization of MInts in the proof trace:
- We add support for parametric sorts in the KORE rich header generation algorithm, because MInt sorts are indeed parametric. To do that we need to have an invariant of topological sorting of the ordinals of sorts, i.e. every sort needs to have an ordinal greater than the ordinals of all its parameters. We can guarantee that by generating the sort ordinals in this way, since all parametric sorts are known statically at compile time.
- We fix a bug on how we pass arguments to the `emit_*_to_proof_trace` functions that emit various events to the proof trace. Previously, when these functions needed to emit a KORE term as part of an event, they would accept a pointer to said KORE term as argument, an in case …
> Fixes for MInt serialization into the proof trace

- bindings/python/ast.cpp
- include/kllvm/binary/ProofTraceParser.h
- lib/binary/ProofTraceParser.cpp
- tools/kore-proof-trace/main.cpp
The Math Proof Team has had an issue with `llvm_rewrite_trace_iterator` where they start iteration in one function, and finish in another function, passing the iterator as an argument to this second function. This second function also generates an Iterable object that is then returned in the first function.
This complex workflow was raising a `Python Segmentation Fault` on the call of `get_next_event` inside our `class LLVMRewriteTraceIterator`. After many hours of debugging, I reached a point where I discovered that the `arities_` of the `kore_header` object were corrupted, and then the parser threw a Segmentation Fault when trying to execute `get_arity`.
I believe the Pybind deleted the `kore_header` object when the function finishes, as it was the only const ref on the function, and …
> Making `proof_trace_parser` and `llvm_rewrite_trace_iterator` use a shared_ptr of `kore_header`

- bindings/c/include/kllvm-c/kllvm-c.h
- bindings/c/lib.cpp
- include/runtime/alloc.h
- include/runtime/collect.h
- include/runtime/header.h
- include/runtime/types.h
- lib/codegen/EmitConfigParser.cpp
- runtime/alloc/arena.cpp
- runtime/util/ConfigurationParser.cpp
- runtime/util/ConfigurationSerializer.cpp
- unittests/runtime-arithmetic/inttest.cpp
- unittests/runtime-collections/lists.cpp
- unittests/runtime-strings/CMakeLists.txt
* some improved function prototypes in header files
* make BLOCK_SIZE a macro
* extract out some basic header file content to its own file that does not declare any undefined symbols
* better support for serialization/deserialization
> a few minor fixes to support the ULM better

- matching/src/main/scala/org/kframework/backend/llvm/matching/Matrix.scala
- test/input/same-name-diff-value/transferFunds.in
- test/output/same-name-diff-value/transferFunds.proof.out.diff
- test/proof/k-files/same-name-diff-value.k
- test/proof/same-name-diff-value.kore
In this PR, we inverse the order in which we create the decision tree when a rule has a side condition. Previously, even when we had 2 or more variables with the same name having different values, the side condition decision trees were generated, and we only evaluated the variables matching after evaluating the side condition. 
After this PR, we inverse this order and evaluate the variables matching first and then the side condition.
This issue was discovered in the context of side conditions proof events being emitted and being true but without ever being applied, as we have a mismatch in the variable names and values.
This PR fixes: https://github.com/Pi-Squared-Inc/pi2/issues/2124
We added a regression test that reproduced this issue, and it's now fixed!
> Only emitting side_conditions if all occurrences of the same variable are equal

- lib/codegen/CreateStaticTerm.cpp
- lib/codegen/CreateTerm.cpp
- lib/codegen/Decision.cpp
- lib/codegen/EmitConfigParser.cpp
When we updated to the version of the llvm backend with opaque pointers, all pointer types become the same type in llvm bitcode. As such, we no longer need bitcast instructions to cast from one pointer type to another. These now redundant instructions can be removed.
> try to delete some probably unneeded bitcasts

- config/llvm_header.inc
- include/runtime/types.h
- lib/codegen/CreateStaticTerm.cpp
- lib/codegen/Decision.cpp
- lib/codegen/EmitConfigParser.cpp
- lib/codegen/Metadata.cpp
This PR is a preparation to improve the thread safety of the llvm backend which attempts to reduce the number of global variables that need to be considered by marking as many of them as read only as possible.
> make many global variables constant

- lib/codegen/CreateStaticTerm.cpp
Fixes a regression introduced in #1167 when mutable bytes are enabled. Hooked functions like `replaceAtBytes` that get called on static byte strings were causing segfaults because they were in read-only memory.
> Don't make static tokens constant

- include/runtime/arena.h
- runtime/alloc/arena.cpp
- runtime/collect/collect.cpp
- runtime/collect/migrate_collection.cpp
- runtime/lto/alloc.cpp
* memory_block_header now a struct member of class arena; next_superblock field deleted
* global function free_all_memory() deleted
* global variable hyperblock_ptr deleted
* global functions make ptr_diff(), move_ptr(), get_arena_semispace_id_of_object(), mem_block_header() now static member functions of class arena
> further refactoring allocation code

- runtime/util/search.cpp
In the final version of the ULM, we want to enforce that semantics are deterministic. We do this using the search feature and the `--execute-to-branch` option which treats all states with more than one successor as final states and does not rewrite them further.
I tested this by running the ethereum test suite with this option and all the tests passed (with a few trivial changes to the semantics). A minor change resulted from this effort: if only a single state is active at a given time, we do not need to do the expensive equality check performed by `erase`. It is sufficient to simply clear the hash set.
> Minor optimization to search

- lib/codegen/CreateStaticTerm.cpp
- lib/codegen/EmitConfigParser.cpp
- matching/src/main/scala/org/kframework/backend/llvm/matching/Generator.scala
- runtime/util/ConfigurationParser.cpp
- test/defn/mint-literal.kore
- test/input/mint-literal.in
- test/output/mint-literal.out.diff
I discovered 2 bugs relating to machine integer literals that are fixed by this PR:
1. If a MInt literal appeared in the initial configuration, its value would be changed by the code that creates the initial configuration term.
2. If  an MInt literal appeared in a rule, the rule would match against the incorrect value of integer.
> Fix some bugs relating to machine integer literals

- lib/codegen/EmitConfigParser.cpp
- runtime/util/ConfigurationParser.cpp
Making this change prevents a memory leak because `free` was never being called previously on this memory.
> use kore_alloc_always_gc instead of malloc when building config

- include/runtime/arena.h
- runtime/alloc/arena.cpp
- runtime/collect/collect.cpp
Replaced algorithm in class arena with one that uses mmap()'d address spaces and demand paging for each semispace and initializes the current semispace of each arena at start time to avoid and the second semispace of each arena at swap time to avoid relying on Undefined Behavior or having an extra test in kore_arena_alloc().
> New allocation algorithm

- bin/llvm-kompile
- bin/llvm-kompile-clang
- include/kllvm/codegen/GCStrategy.h
- include/kllvm/codegen/Options.h
- lib/codegen/CreateTerm.cpp
- lib/codegen/Options.cpp
- lib/passes/CMakeLists.txt
- lib/passes/GCStrategy.cpp
- test/defn/imp.kore
- test/lit.cfg.py
- tools/llvm-kompile-codegen/main.cpp
This PR adds a new GCStrategy, that treats any pointer with address space other than 0 as a pointer to managed memory.
We extent class GCStrategy in llvm/IR/GCStrategy.h, and register the new GCStrategy.
> New GC strategy.

- include/runtime/alloc.h
- include/runtime/arena.h
- runtime/alloc/arena.cpp
- runtime/lto/alloc.cpp
Dead code eliminated:
youngspace_size()
arena_size()
union memory_block_header and associated functionality replaced. The semispace id is now stored in the last byte of the hyperblock which simplifies address computations.
> Further allocator refactoring

- .github/workflows/release.yml
- .github/workflows/test.yml
- include/runtime/header.h
- runtime/collect/collect.cpp
- runtime/collect/migrate_collection.cpp
- runtime/collect/migrate_static_roots.cpp
We move the empty map/list/set allocations to be allocated using `new` and never deallocated or relocated in order to assist in the thread safety of the llvm backend. When we make each allocation arena thread-local, this change will be required, otherwise garbage collection in one thread will corrupt collections in other threads.
> do not garbage collect empty map/list/set

- runtime/alloc/arena.cpp
Use munmap() to release unused part of mmap()ed address space in arena::initialize_semispace() to reduce the risk of running out of mmap()able address space in a multithreaded situation.
> Release unused address space

- include/runtime/arena.h
The destructor for arena now munmap()s any mapped address space. This is aimed at threads that may exit while the address space remains active for other threads.
> Release address space on thread exit

- cmake/FixHomebrew.cmake
It seems that `lld` can't find the libs correctly in macOS SDK < 15 and this is blocking K's release:
https://github.com/runtimeverification/k/actions/runs/12327347003/job/34409254563
> Set lld as macOS linker only if SDK is greater or equal to 15

- include/runtime/proof_trace_writer.h
This PR fixes a bug in calls to calls to `side_condition_event_callback`. Every time such a call should occur, the `rewrite_event_callback` is invoked instead.
This is due to a bug in the method that builds substitutions, and calls a callback once the substitution has the required size. Instead of conditionally calling either the rewrite callback or the sidecondition callback, it always calls the rewrite one.
This PR fixes the bug.
> Callbacks: Fix side-condition events when arity is non-null

- include/runtime/arena.h
- runtime/alloc/arena.cpp
- runtime/collect/collect.cpp
- runtime/lto/alloc.cpp
The condition for requesting collections is replaced by requesting a collection
if an allocation passes a tripwire. This tripwire is initially set at MIN_SPACE
and is recalculated after each garbage collation as max(MIN_SPACE, |live data|).
This avoids a potential issue with the old behavior where collections were
trigged by allocating in the last 1 MB of previously allocated semispace, even
if little garbage is being generated, or not collecting frequently enough if
a period of low garbage generation is followed by a period of high garbage
generation, affecting cache performance.
Furthermore, garbage collections are only trigged by allocations in youngspace.
Allocations in oldspace no longer trigger collections since oldspace collections
are handled during a youngspace collection. …
> Gc refactor3 rebased

- include/runtime/proof_trace_writer.h
Avoid setup and tear-down costs for current_call_event_ and current_rewrite_event_ by providing members to replace and reuse rather than using optional::reset() and emplace().
> reduce heap allocations and deallocations in proof_trace_callback_writer

- config/llvm_header.inc
- debug/kgdb.py
- runtime/collections/hash.cpp
- runtime/collections/kelemle.cpp
This is intended to fix crashes when the llvm backend manipulates machine integers of sizes 8, 16, and 128.
> add cases for MInt{8}, MInt{16}, and MInt{128}

- include/runtime/arena.h
- runtime/collect/collect.cpp
This is needed as in Pi2 we discovered that our GEth client, switches threads and not reuses the arena's mapped size in by other thread, instead, allocate the same amount at every switching making it pretty easy to overflow the memory usage.
> Adding `munmap_arena_and_reset` and calling it to all semispaces when `free_all_kore_mem`

- runtime/collect/collect.cpp
Ideally, when we call this function, we want to clean everything, including all semispaces to free the memory for future usage. However, we found a bug com a few `ValidBlocks` tests from Ethereum BlockchainTests that throws an error when collecting the old generation when we had called this `free_all_kore_mem` before. This issue doesn't happen for the GeneralStateTests, that's why we didn't find it before.
This modification is safe and still keeps the benefits of freeing a lot of space, as the majority of allocated memory observed in the tests are stored in the young generation. 
We'll go back to investigate this GC bug soon.
> Update `free_all_kore_mem` to avoid memory corruption

- include/runtime/arena.h
- runtime/collect/collect.cpp
The `allocation_ptr` was the missing variable we needed to reset to correctly reset the whole semispace GC strategy. This PR fixes issue #1204 where the `allocation_ptr` kept an old value from a previous GC iteration that was often higher than the current `oldspace` semispace, making it impossible to be allocated or to clean the memory using it on `scan_ptr`
> Fixing `munmap_arena_and_reset` issue by reseting `allocation_ptr`

- include/runtime/collect.h
- runtime/collect/collect.cpp
This PR splits the implementation of `free_all_kore_mem` between 2 functions:
- `free_all_kore_mem`
- `reset_munmap_all_arenas`
The idea is only to use the second one when necessary, instead of executing its content every time we call the first.
> Implementing reset_munmap_all_arenas
