- .gitignore
- .gitmodules
- runtime/datastructures/Cargo.toml
- runtime/datastructures/src/decls.rs
- runtime/datastructures/src/hook_list.rs
- runtime/datastructures/src/hook_map.rs
- runtime/datastructures/src/hook_set.rs
- runtime/datastructures/src/lib.rs
- runtime/header.ll
@bmmoore your review of the rust code would be appreciated. @theo25 feel free to review the function signatures and changes to header.ll as well as the test coverage and any rust you feel you can understand.
> add map, list, set hooks in rust

- include/kllvm/codegen/CreateTerm.h
- lib/codegen/CreateTerm.cpp
- runtime/arithmetic/CMakeLists.txt
- runtime/arithmetic/int.cpp
- runtime/datastructures/Cargo.toml
- runtime/datastructures/src/decls.rs
- runtime/datastructures/src/hook_list.rs
- runtime/datastructures/src/hook_map.rs
- runtime/datastructures/src/hook_set.rs
- runtime/datastructures/src/lib.rs
- runtime/move_int.ll
- test/imp.ll
- test/test.ll
- unittests/runtime-arithmetic/inttest.cpp
Changes hooks and functions to return their value and abort on error, so that they can be tail called by other functions.
> hook and function refactoring

- ciscript
- include/kllvm/codegen/CreateTerm.h
- include/kllvm/codegen/Decision.h
- lib/codegen/CreateTerm.cpp
- lib/codegen/Decision.cpp
- lib/codegen/DecisionParser.cpp
- lib/codegen/EmitConfigParser.cpp
- matching/src/Pattern.hs
- matching/src/Pattern/Gen.hs
- matching/src/Pattern/Parser.hs
- matching/test/Spec.hs
- runtime/arithmetic/int.cpp
- runtime/datastructures/src/hook_list.rs
- test/test2.kore
- test/test3.kore
- unittests/runtime-arithmetic/inttest.cpp
* pattern matching on Ints and Strings
* new array hooks and array bugfixes
* improve performance of haskell
* as patterns
* compute best column using "computeScore" function
* various minor bugfixes
> Bug fixes and features required for IELE

- include/runtime/alloc.h
- include/runtime/header.h
- lib/codegen/CreateTerm.cpp
- lib/codegen/EmitConfigParser.cpp
- runtime/alloc/alloc.c
- runtime/alloc/collect.c
- runtime/configurationparser/ConfigurationPrinter.cpp
- runtime/datastructures/src/decls.rs
- runtime/datastructures/src/lib.rs
- runtime/equality.ll
- runtime/hash.ll
- runtime/main.ll
- runtime/move_int.ll
- runtime/strings/strings.cpp
- unittests/runtime-strings/bytestest.cpp
- unittests/runtime-strings/stringtest.cpp
Also allocates rust memory and gmp memory directly to the old generation using the same fast allocation function. Eventually we will have to collect all three of these, but that's not part of this PR.
> Promote old objects to old generation (not yet collected)

- bin/llvm-kompile
- llvm6.sh
I removed the rust aliases from the llvm-kompile script.
> A quick fix for the mac build.

- matching/src/Pattern.hs
The results of running lint and stylish over the code.
> Syntactic refactoring.

- Jenkinsfile
> jenkins pipeline build

- lib/ast/AST.cpp
This is a fix for kframework/k#280
> exclude another category of axiom

- matching/package.yaml
- matching/src/Everything.hs
- matching/src/Pattern.hs
- matching/src/Pattern/Parser.hs
- matching/src/Pattern/Type.hs
- matching/stack.yaml
- matching/test/Spec.hs
Radu's PR used the wrong commit of kore, so I updated to the latest master. Fortunately very nearly all of the work was already done.
> update the rest of the way to latest kore

- ciscript
- matching/src/Everything.hs
- test/test13.kore
We were not expanding or patterns correctly if an Or was an immediate child of an As. This should fix that.
> Fix bug involving or and as

- runtime/meta/ffi.cpp
- unittests/runtime-ffi/ffi.cpp
- unittests/runtime-ffi/lib/foreign.cpp
Implements the variadic FFI call hook
> FFI Variadic Hook

- Dockerfile
- INSTALL.md
- lib/codegen/DecisionParser.cpp
- matching/src/main/scala/org/kframework/backend/llvm/matching/Matching.scala
- tools/llvm-kompile-codegen/CMakeLists.txt
- tools/llvm-kompile-codegen/main.cpp
- unittests/compiler/CMakeLists.txt
* fix a bug with file names that are too long for linux
* significantly improve yaml deserialization performance during codegen.
> Improvements to codegen for execution semantics

- CMakeLists.txt
- bin/llvm-kompile-clang
> fixes for ffi on mac os

- matching/src/main/scala/org/kframework/backend/llvm/matching/Heuristics.scala
This PR will contain all the heuristics that are described in Maranget's paper
> Heuristic a

- matching/src/main/scala/org/kframework/backend/llvm/matching/Heuristics.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/Matrix.scala
- matching/tree_stats.py
Includes:
* cleanup of code for heuristics that need the entire matrix
* priority inversion code for invalid columns
* improve getBest function and remove hack
* Improved logging
* more tree stats
> Clean up and refactor scoring

- lib/codegen/Decision.cpp
LLVM 8 has a bug where it will emit names for local variables that are longer than its own maximum identifier length, which causes the parser for .ll files to crash. We work around this issue by simply truncating all the variables' names.
> limit max length of identifiers so as to avoid llvm 8 bug

- runtime/configurationparser/ConfigurationPrinter.cpp
@mickyabir FYI.
I need to get this into K tonight so I'm going to merge without review, but please comment tomorrow if you have concerns and I'll address them in a future PR.
> fix printer on escapes

- gdb/kllvm.py
- include/runtime/alloc.h
- include/runtime/collect.h
- include/runtime/header.h
- lib/codegen/CreateTerm.cpp
- runtime/collect/CMakeLists.txt
- runtime/collect/collect.cpp
- runtime/collect/migrate_collection.cpp
- runtime/collect/migrate_roots.cpp
- runtime/main/main.ll
- unittests/runtime-collections/lists.cpp
> Garbage collect lists

- include/runtime/alloc.h
- include/runtime/collect.h
- include/runtime/header.h
- runtime/alloc/alloc.cpp
- runtime/alloc/arena.cpp
- runtime/collect/collect.cpp
- runtime/collect/migrate_collection.cpp
- runtime/collect/migrate_roots.cpp
- unittests/runtime-collections/lists.cpp
> Garbage collect maps and sets

- matching/pom.xml
- matching/src/main/scala/org/kframework/backend/llvm/matching/Generator.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/Matrix.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/Pattern.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/SortCategory.scala
Integration testing found a few minor bugs in the last PR.
> Fix bugs in usefulness algorithm

- lib/codegen/Decision.cpp
- runtime/finish_rewriting.ll
- test/defn/test31.kore
- test/input/test31.in.kore
- test/output/test31.out.diff.kore
This should significantly improve debugability when the llvm backend gets stuck evaluating a function.
> Print stuck function instead of aborting

- include/runtime/header.h
- runtime/configurationparser/ConfigurationPrinter.cpp
- runtime/finish_rewriting.ll
@ehildenb can you try this out and let me know if this helps you?
> Better error message when semantics is used as a library and function gets stuck

- bin/llvm-kompile-clang
we propagate -fno-omit-frame-pointer to llc
> Frame pointer elimination with llc

- lib/codegen/CreateTerm.cpp
Fixes runtimeverification/firefly#572
> check if pointer is null before dyn_casting it

- include/kllvm/codegen/Decision.h
- lib/codegen/Decision.cpp
I forgot to push these changes before I merged.
> minor improvements to topological sort PR

- bin/llvm-kompile-clang
This should fix the failing K master build.
> add -liconv on mac os

- unittests/runtime-ffi/CMakeLists.txt
- unittests/runtime-io/CMakeLists.txt
- unittests/runtime-strings/CMakeLists.txt
- unittests/runtime-strings/stringtest.cpp
I tested that this fixes the issue with the build of the llvm backend on mac os.
> iconv on mac os bugfix

- include/runtime/header.h
- runtime/io/io.cpp
- runtime/strings/strings.cpp
- unittests/runtime-io/io.cpp
@dwightguth What would be the best way to automatically test this? I tested it only manually, using hardcoded values for the two variables.
> KREFLECTION.argv

- runtime/arithmetic/int.cpp
- runtime/collect/migrate_roots.cpp
Fixes #373 
@gtrepta please test this against the original defect in Firefly. I can confirm that it fixes the issue you reported.
> randState is a gc root

- lib/ast/AST.cpp
This fixes a bug that is blocking kframework/k#1743
> fix bug involving macro expansion

- matching/src/main/scala/org/kframework/backend/llvm/matching/Heuristics.scala
- matching/src/main/scala/org/kframework/backend/llvm/matching/Matrix.scala
Contains 3 changes:
* a refactoring of the b heuristic
* a bugfix for the r heuristic
* a new heuristic, o, that seems to show some promise when applied to semantics that behave pathologically on the `qba` series of heuristics.
> Improvements to matching heuristics

- .github/workflows/test.yml
- nix/llvm-backend.nix
- runtime/configurationparser/ConfigurationParser.cpp
- test.nix
This pull request fixes the build on macOS < 10.14 and runs the tests with Nix on macOS.
> Build with Nix on macOS

- default.nix
Part of https://github.com/kframework/k/issues/1864
> Add ref = "main"; to default.nix

- .github/workflows/test.yml
- default.nix
- nix/llvm-backend.nix
This allows us to build the Nix package with LTO, and populates the cache.
> Add flag to build Nix package with LTO

- INSTALL.md
- README.md
Adds a brief note on how to run the tests to `INSTALL.md`.
> add info on running test suite

- CMakeLists.txt
- default.nix
- flake.lock
- flake.nix
- nix/devShell.nix
- nix/llvm-backend-matching.nix
- nix/overlay.nix
- shell.nix
Eventually I would like to flakify this repository. However, thought the scope of that would be a little too big. So I'm creating this PR which should be a smaller refactor of the existing code. But sill be much more compatible with a flake as most of the complexity is delegated to overlays, rather than having a lot of logic in default.nix
cc @ttuegel
> Cleanup cmake and nix

- tools/kore-strip/main.cpp
This is a hotfix for the issue that's currently breaking the K release build; the underlying issue is #507.
> Fix compiler warnings on Arch

- matching/README.md
I would really appreciate anyone interested in developing on the llvm backend who is not already familiar with this material to review this PR carefully with an eye towards its suitability to newcomers. The goal is that it should be able to fully explain how matching is compiled on all the cases we cover, without needing to refer to the original codebase.
> add formal documentation for decision tree algorithm

- ciscript
- cmake/SetTriple.cmake
- cmake/guess-target-property.sh
- test/lit.cfg.py
This fixes some minor issues that have cropped up on macOS / arm since the last time I went through building the backend.
> Minor Apple Silicon fixes

- matching/README.md
We discussed this line on Slack previously, but the fix never made it back into the actual documentation.
> Fix line in matching readme

- .github/workflows/release.yml
> Fix no .git directory

- .github/workflows/test-flake.yml
- .github/workflows/update.yml
This mirrors the changes made here to fix this error in KEVM: https://github.com/runtimeverification/evm-semantics/pull/1458/commits/7a292eb20c0639b7f578bcd762bf13ecb6c6ade0
> Fix cachix token

- .github/workflows/test-flake.yml
- .github/workflows/update.yml
https://github.com/cachix/cachix-action/issues/138
> Fixing breaking nix update for cachix

- bin/llvm-kompile
> Add `NIX_LLVM_KOMPILE_LIBS` to `llvm-kompile`

- docs/proof-trace.md
- runtime/main/main.ll
- runtime/util/util.cpp
> Version header for proof hints

- docs/proof-trace.md
- include/kllvm/codegen/ProofEvent.h
- lib/codegen/Decision.cpp
- lib/codegen/ProofEvent.cpp
> Proof hints for side conditions

- docs/proof-trace.md
- include/kllvm/codegen/ProofEvent.h
- lib/codegen/CreateTerm.cpp
- lib/codegen/ProofEvent.cpp
> Hook event location information

- .github/workflows/test-flake.yml
- bin/CMakeLists.txt
- bin/llvm-kompile
- bin/llvm-kompile-clang
- include/CMakeLists.txt
for https://github.com/runtimeverification/k/issues/3675
> Move some stray install locations into the `kllvm` subdirectories

- bindings/python/ast.cpp
- docs/proof-trace.md
- include/kllvm/binary/ProofTraceParser.h
- include/kllvm/codegen/ProofEvent.h
- lib/binary/ProofTraceParser.cpp
- lib/codegen/Decision.cpp
- lib/codegen/ProofEvent.cpp
- runtime/util/util.cpp
- test/output/imp-proof.out.diff
The new event carries the result of the side condition check.
> Adding a side condition exit event to the proof hint trace

- debug/kgdb.py
https://github.com/runtimeverification/k/issues/4576
More fixes that were missed in #1123 and #1120
> Update KElem names in kgdb

- config/llvm_header.inc
- matching/src/main/scala/org/kframework/backend/llvm/matching/pattern/SortCategory.scala
This is used by the pattern matcher when nonlinear matching occurs.
> Equality function on mint

- CMakeLists.txt
This addresses a problem in the K build for Homebrew
> Update CMake minimum version to 3.5
